/**
 * AUTO-GENERATED by scripts/gen-ksc-evaluator.ts — do not edit.
 *
 * KSC Compiled Evaluator — fully static AG pipeline.
 * KSCDNode: standalone decorated node with typed cache fields,
 * switch-based dispatch, and direct equation function calls.
 * No DNode inheritance, no Map-based caching, no runtime compilation.
 */

import type { KSNode } from '../ast-schema/generated/index.js';
import { getChildFields } from '../ast-schema/generated/index.js';
import type { KSCAttrMap } from '../ksc-behavior/attr-types.js';
import type { Ctx } from '../ksc-behavior/ctx.js';
import type { KindDefinition, CheckerDiagnostic, AttributeDepGraph } from '../ksc-behavior/types.js';

// Static equation imports — binder
import {
  type DefIdCounter,
  eq_kindDefs_CompilationUnit,
  eq_kindDefs_default,
  eq_defEnv_root,
  eq_defLookup,
  project_binder,
} from '../ksc-behavior/binder.js';

// Static equation imports — checker
import {
  eq_kindAnnotations_VariableDeclaration,
  eq_kindAnnotations_default,
  eq_noImportsContext_rootValue,
  eq_noImportsContext,
  eq_importViolation_Identifier,
  eq_importViolation_default,
  eq_allViolations_contribute,
  eq_allViolations_combine,
  project_checker,
} from '../ksc-behavior/checker.js';

// ── KSCDNode: typed cache + switch dispatch ──

const ATTR_NAMES: ReadonlySet<string> = new Set([
  'kindDefs',
  'defEnv',
  'defLookup',
  'kindAnnotations',
  'noImportsContext',
  'importViolation',
  'allViolations',
]);

export class KSCDNode implements Ctx {
  readonly node: KSNode;
  readonly parent: KSCDNode | undefined;
  readonly children: readonly KSCDNode[];
  readonly index: number;
  readonly isRoot: boolean;
  readonly prev: KSCDNode | undefined;
  readonly next: KSCDNode | undefined;
  readonly fieldName: string | undefined;

  private _counter: DefIdCounter;

  // Typed cache — undefined = not yet computed
  private _c_kindDefs: KindDefinition[] | undefined = undefined;
  private _c_defEnv: Map<string, KindDefinition> | undefined = undefined;
  private _c_defLookup: ((name: string) => KindDefinition | undefined) | undefined = undefined;
  private _c_kindAnnotations: KindDefinition[] | undefined = undefined;
  private _c_noImportsContext: KindDefinition | null | undefined = undefined;
  private _c_importViolation: CheckerDiagnostic | null | undefined = undefined;
  private _c_allViolations: CheckerDiagnostic[] | undefined = undefined;

  private _cyc = new Set<string>();

  constructor(
    node: KSNode,
    parent: KSCDNode | undefined,
    children: KSCDNode[],
    index: number,
    fieldName: string | undefined,
    counter: DefIdCounter,
  ) {
    this.node = node;
    this.parent = parent;
    this.children = children;
    this.index = index;
    this.isRoot = !parent;
    this.prev = undefined;
    this.next = undefined;
    this.fieldName = fieldName;
    this._counter = counter;
  }

  // ── Attribute access (string-based, for serialization) ──

  attr<K extends string & keyof KSCAttrMap>(name: K): KSCAttrMap[K];
  attr(name: string): any {
    switch (name) {
      case 'kindDefs': return this.kindDefs();
      case 'defEnv': return this.defEnv();
      case 'defLookup': return this.defLookup();
      case 'kindAnnotations': return this.kindAnnotations();
      case 'noImportsContext': return this.noImportsContext();
      case 'importViolation': return this.importViolation();
      case 'allViolations': return this.allViolations();
      default: throw new Error(`Unknown attribute '${name}' on ${this.node.kind ?? 'node'}`);
    }
  }

  hasAttr(name: string): boolean {
    switch (name) {
      case 'kindDefs': return this._c_kindDefs !== undefined;
      case 'defEnv': return this._c_defEnv !== undefined;
      case 'defLookup': return this._c_defLookup !== undefined;
      case 'kindAnnotations': return this._c_kindAnnotations !== undefined;
      case 'noImportsContext': return this._c_noImportsContext !== undefined;
      case 'importViolation': return this._c_importViolation !== undefined;
      case 'allViolations': return this._c_allViolations !== undefined;
      default: return false;
    }
  }

  get attrNames(): ReadonlySet<string> {
    return ATTR_NAMES;
  }

  _setCache(name: string, value: unknown): void {
    switch (name) {
      case 'kindDefs': this._c_kindDefs = value as KindDefinition[]; break;
      case 'defEnv': this._c_defEnv = value as Map<string, KindDefinition>; break;
      case 'defLookup': this._c_defLookup = value as (name: string) => KindDefinition | undefined; break;
      case 'kindAnnotations': this._c_kindAnnotations = value as KindDefinition[]; break;
      case 'noImportsContext': this._c_noImportsContext = value as KindDefinition | null; break;
      case 'importViolation': this._c_importViolation = value as CheckerDiagnostic | null; break;
      case 'allViolations': this._c_allViolations = value as CheckerDiagnostic[]; break;
    }
  }

  // ── Structural queries ──

  parentIs(kind: string, field?: string): boolean {
    if (!this.parent) return false;
    if (this.parent.node.kind !== kind) return false;
    if (field !== undefined) return this.fieldName === field;
    return true;
  }

  childAt(field: string): KSCDNode | undefined {
    return (this.children as KSCDNode[]).find(c => c.fieldName === field);
  }

  childrenAt(field: string): KSCDNode[] {
    return (this.children as KSCDNode[]).filter(c => c.fieldName === field);
  }

  // ── Direct typed attribute methods ──

  kindDefs(): KindDefinition[] {
    if (this._c_kindDefs !== undefined) return this._c_kindDefs;
    if (this._cyc.has('kindDefs')) throw new Error(`Circular attribute access: 'kindDefs' on ${this.node.kind}`);
    this._cyc.add('kindDefs');
    try {
      switch (this.node.kind) {
        case 'CompilationUnit': return this._c_kindDefs = eq_kindDefs_CompilationUnit(this, this._counter);
        default: return this._c_kindDefs = eq_kindDefs_default();
      }
    } finally { this._cyc.delete('kindDefs'); }
  }

  defEnv(): Map<string, KindDefinition> {
    if (this._c_defEnv !== undefined) return this._c_defEnv;
    if (this._cyc.has('defEnv')) throw new Error(`Circular attribute access: 'defEnv' on ${this.node.kind}`);
    this._cyc.add('defEnv');
    try {
      if (this.isRoot) {
        return this._c_defEnv = eq_defEnv_root(this);
      }
      return this._c_defEnv = this.parent!.defEnv();
    } finally { this._cyc.delete('defEnv'); }
  }

  defLookup(): (name: string) => KindDefinition | undefined {
    if (this._c_defLookup !== undefined) return this._c_defLookup;
    if (this._cyc.has('defLookup')) throw new Error(`Circular attribute access: 'defLookup' on ${this.node.kind}`);
    this._cyc.add('defLookup');
    try {
      return this._c_defLookup = eq_defLookup(this);
    } finally { this._cyc.delete('defLookup'); }
  }

  kindAnnotations(): KindDefinition[] {
    if (this._c_kindAnnotations !== undefined) return this._c_kindAnnotations;
    if (this._cyc.has('kindAnnotations')) throw new Error(`Circular attribute access: 'kindAnnotations' on ${this.node.kind}`);
    this._cyc.add('kindAnnotations');
    try {
      switch (this.node.kind) {
        case 'VariableDeclaration': return this._c_kindAnnotations = eq_kindAnnotations_VariableDeclaration(this, this.node);
        default: return this._c_kindAnnotations = eq_kindAnnotations_default();
      }
    } finally { this._cyc.delete('kindAnnotations'); }
  }

  noImportsContext(): KindDefinition | null {
    if (this._c_noImportsContext !== undefined) return this._c_noImportsContext;
    if (this._cyc.has('noImportsContext')) throw new Error(`Circular attribute access: 'noImportsContext' on ${this.node.kind}`);
    this._cyc.add('noImportsContext');
    try {
      if (this.isRoot) {
        return this._c_noImportsContext = eq_noImportsContext_rootValue;
      }
      const result = eq_noImportsContext(this.parent!);
      if (result !== undefined) return this._c_noImportsContext = result;
      return this._c_noImportsContext = this.parent!.noImportsContext();
    } finally { this._cyc.delete('noImportsContext'); }
  }

  importViolation(): CheckerDiagnostic | null {
    if (this._c_importViolation !== undefined) return this._c_importViolation;
    if (this._cyc.has('importViolation')) throw new Error(`Circular attribute access: 'importViolation' on ${this.node.kind}`);
    this._cyc.add('importViolation');
    try {
      switch (this.node.kind) {
        case 'Identifier': return this._c_importViolation = eq_importViolation_Identifier(this, this.node);
        default: return this._c_importViolation = eq_importViolation_default();
      }
    } finally { this._cyc.delete('importViolation'); }
  }

  allViolations(): CheckerDiagnostic[] {
    if (this._c_allViolations !== undefined) return this._c_allViolations;
    if (this._cyc.has('allViolations')) throw new Error(`Circular attribute access: 'allViolations' on ${this.node.kind}`);
    this._cyc.add('allViolations');
    try {
      let result = eq_allViolations_contribute(this);
      for (const child of this.children) {
        result = eq_allViolations_combine(result, child.allViolations());
      }
      return this._c_allViolations = result;
    } finally { this._cyc.delete('allViolations'); }
  }

}

// ── Schema-aware tree builder ──

function buildKSCTree(root: KSNode, counter: DefIdCounter): KSCDNode {
  function build(
    raw: KSNode,
    parent: KSCDNode | undefined,
    index: number,
    fieldName: string | undefined,
  ): KSCDNode {
    const children: KSCDNode[] = [];
    const dnode = new KSCDNode(raw, parent, children, index, fieldName, counter);

    const fields = getChildFields(raw.kind);
    let childIndex = 0;
    for (const field of fields) {
      const val = (raw as any)[field];
      if (val == null) continue;
      if (Array.isArray(val)) {
        for (const item of val) {
          if (item == null) continue;
          children.push(build(item as KSNode, dnode, childIndex++, field));
        }
      } else {
        children.push(build(val as KSNode, dnode, childIndex++, field));
      }
    }

    for (let i = 0; i < children.length; i++) {
      (children[i] as any).prev = i > 0 ? children[i - 1] : undefined;
      (children[i] as any).next = i < children.length - 1 ? children[i + 1] : undefined;
    }

    return dnode;
  }

  return build(root, undefined, -1, undefined);
}

// ── Static dependency graph ──

const KSC_STATIC_DEP_GRAPH: AttributeDepGraph = {
  attributes: [
    'kindDefs',
    'defEnv',
    'defLookup',
    'kindAnnotations',
    'noImportsContext',
    'importViolation',
    'allViolations',
  ],
  edges: [
    ['defEnv', 'kindDefs'],
    ['defLookup', 'defEnv'],
    ['kindAnnotations', 'defLookup'],
    ['noImportsContext', 'kindAnnotations'],
    ['importViolation', 'noImportsContext'],
    ['allViolations', 'importViolation'],
  ],
  order: [
    'kindDefs',
    'defEnv',
    'defLookup',
    'kindAnnotations',
    'noImportsContext',
    'importViolation',
    'allViolations',
  ],
  specOwnership: {
    kindDefs: 'ksc-binder',
    defEnv: 'ksc-binder',
    defLookup: 'ksc-binder',
    kindAnnotations: 'ksc-checker',
    noImportsContext: 'ksc-checker',
    importViolation: 'ksc-checker',
    allViolations: 'ksc-checker',
  },
  declarations: {
    kindDefs: { direction: 'syn' },
    defEnv: { direction: 'inh' },
    defLookup: { direction: 'syn' },
    kindAnnotations: { direction: 'syn' },
    noImportsContext: { direction: 'inh' },
    importViolation: { direction: 'syn' },
    allViolations: { direction: 'collection' },
  },
};

// ── Evaluation ──

export interface EvaluationResult {
  definitions: KindDefinition[];
  diagnostics: CheckerDiagnostic[];
  getDepGraph(): AttributeDepGraph;
}

export function evaluate(root: KSNode): EvaluationResult {
  const counter: DefIdCounter = { value: 0 };
  const dnodeRoot = buildKSCTree(root, counter);
  const definitions = project_binder(dnodeRoot);
  const diagnostics = project_checker(dnodeRoot);
  return { definitions, diagnostics, getDepGraph: () => KSC_STATIC_DEP_GRAPH };
}

/** Build a KSCDNode tree for direct attribute inspection (used by tests). */
export function buildTree(root: KSNode): KSCDNode {
  const counter: DefIdCounter = { value: 0 };
  return buildKSCTree(root, counter);
}
