// Auto-generated by scripts/generate-lessons.mjs
// DO NOT EDIT MANUALLY — regenerate with: npm run generate:lessons

import { Lesson, Part } from './types';

import { lesson as lesson0 } from './1-1-hello-world.generated';
import { lesson as lesson1 } from './2-1-no-console.generated';
import { lesson as lesson2 } from './2-2-immutable-bindings.generated';
import { lesson as lesson3 } from './2-3-no-mutation.generated';
import { lesson as lesson4 } from './2-4-combining-kinds.generated';
import { lesson as lesson5 } from './2-5-refactor-to-pure.generated';

export const lessons: Lesson[] = [
  lesson0,
  lesson1,
  lesson2,
  lesson3,
  lesson4,
  lesson5,
].sort((a, b) =>
  a.partNumber === b.partNumber
    ? a.lessonNumber - b.lessonNumber
    : a.partNumber - b.partNumber
);

export const parts: Part[] = lessons.reduce((acc, lesson) => {
  let part = acc.find(p => p.number === lesson.partNumber);
  if (!part) {
    part = { number: lesson.partNumber, title: lesson.partTitle, lessons: [] };
    acc.push(part);
  }
  part.lessons.push(lesson);
  return acc;
}, [] as Part[]);

export function getLessonBySlug(slug: string): Lesson | undefined {
  return lessons.find(l => l.slug === slug);
}

export function getNextLesson(currentSlug: string): Lesson | undefined {
  const index = lessons.findIndex(l => l.slug === currentSlug);
  return index >= 0 && index < lessons.length - 1 ? lessons[index + 1] : undefined;
}

export function getPrevLesson(currentSlug: string): Lesson | undefined {
  const index = lessons.findIndex(l => l.slug === currentSlug);
  return index > 0 ? lessons[index - 1] : undefined;
}
