/**
 * Schema-first node definitions for the KSC AST.
 *
 * AUTO-GENERATED by scripts/gen-node-defs.ts from ast.ts.
 * This is the single source of truth for node types.
 *
 * Each defineNode()/defineLeaf() call produces:
 *   - Runtime schema entry (kind, child fields, prop fields)
 *   - TypeScript type via InferNode<typeof Def>
 */

import {
  defineNode, defineLeaf, child, optChild, list, prop,
  createNodeSchema,
} from '../../libs/ag-schema/src/index.js';
import type { InferNode, NodeDef } from '../../libs/ag-schema/src/index.js';

// ═══════════════════════════════════════════════════════════════════════
// Base type (re-exported from ast.ts)
// ═══════════════════════════════════════════════════════════════════════

export { KSNodeBase } from './ast.js';

// ═══════════════════════════════════════════════════════════════════════
// Node definitions (nodes with named fields)
// ═══════════════════════════════════════════════════════════════════════

export const ProgramDef = defineNode('Program', {
  compilationUnits: list<KSCompilationUnit>(),
});

export const CompilationUnitDef = defineNode('CompilationUnit', {
  fileName: prop<string>(),
  isDeclarationFile: prop<boolean>(),
  sourceText: prop<string>(),
  lineStarts: prop<readonly number[]>(),
});

export const TypeAliasDeclarationDef = defineNode('TypeAliasDeclaration', {
  name: child<KSIdentifier>(),
  typeParameters: list(),
  type: child(),
  modifiers: list(),
});

export const InterfaceDeclarationDef = defineNode('InterfaceDeclaration', {
  name: child<KSIdentifier>(),
  typeParameters: list(),
  members: list(),
  heritageClauses: list(),
  modifiers: list(),
});

export const FunctionDeclarationDef = defineNode('FunctionDeclaration', {
  name: optChild<KSIdentifier>(),
  typeParameters: list(),
  parameters: list(),
  type: optChild(),
  body: optChild(),
  modifiers: list(),
  asteriskToken: optChild(),
});

export const ClassDeclarationDef = defineNode('ClassDeclaration', {
  name: optChild<KSIdentifier>(),
  typeParameters: list(),
  members: list(),
  heritageClauses: list(),
  modifiers: list(),
});

export const EnumDeclarationDef = defineNode('EnumDeclaration', {
  name: child<KSIdentifier>(),
  members: list(),
  modifiers: list(),
});

export const VariableStatementDef = defineNode('VariableStatement', {
  declarationList: child<KSVariableDeclarationList>(),
  modifiers: list(),
});

export const VariableDeclarationListDef = defineNode('VariableDeclarationList', {
  declarations: list<KSVariableDeclaration>(),
  isConst: prop<boolean>(),
  isLet: prop<boolean>(),
});

export const VariableDeclarationDef = defineNode('VariableDeclaration', {
  name: child(),
  type: optChild(),
  initializer: optChild(),
});

export const ImportDeclarationDef = defineNode('ImportDeclaration', {
  importClause: optChild(),
  moduleSpecifier: child(),
});

export const ImportClauseDef = defineNode('ImportClause', {
  isTypeOnly: prop<boolean>(),
  name: optChild<KSIdentifier>(),
  namedBindings: optChild(),
});

export const NamedImportsDef = defineNode('NamedImports', {
  elements: list(),
});

export const ImportSpecifierDef = defineNode('ImportSpecifier', {
  isTypeOnly: prop<boolean>(),
  name: child<KSIdentifier>(),
  propertyName: optChild<KSIdentifier>(),
});

export const NamespaceImportDef = defineNode('NamespaceImport', {
  name: child<KSIdentifier>(),
});

export const ExportDeclarationDef = defineNode('ExportDeclaration', {
  isTypeOnly: prop<boolean>(),
  exportClause: optChild(),
  moduleSpecifier: optChild(),
});

export const ExportAssignmentDef = defineNode('ExportAssignment', {
  expression: child(),
  isExportEquals: prop<boolean>(),
});

export const BlockDef = defineNode('Block', {
  statements: list(),
});

export const ExpressionStatementDef = defineNode('ExpressionStatement', {
  expression: child(),
});

export const ReturnStatementDef = defineNode('ReturnStatement', {
  expression: optChild(),
});

export const IfStatementDef = defineNode('IfStatement', {
  expression: child(),
  thenStatement: child(),
  elseStatement: optChild(),
});

export const ForStatementDef = defineNode('ForStatement', {
  initializer: optChild(),
  condition: optChild(),
  incrementor: optChild(),
  statement: child(),
});

export const ForOfStatementDef = defineNode('ForOfStatement', {
  initializer: child(),
  expression: child(),
  statement: child(),
});

export const ForInStatementDef = defineNode('ForInStatement', {
  initializer: child(),
  expression: child(),
  statement: child(),
});

export const WhileStatementDef = defineNode('WhileStatement', {
  expression: child(),
  statement: child(),
});

export const DoStatementDef = defineNode('DoStatement', {
  expression: child(),
  statement: child(),
});

export const SwitchStatementDef = defineNode('SwitchStatement', {
  expression: child(),
  caseBlock: child(),
});

export const ThrowStatementDef = defineNode('ThrowStatement', {
  expression: child(),
});

export const TryStatementDef = defineNode('TryStatement', {
  tryBlock: child(),
  catchClause: optChild(),
  finallyBlock: optChild(),
});

export const CallExpressionDef = defineNode('CallExpression', {
  expression: child(),
  typeArguments: list(),
  arguments: list(),
});

export const PropertyAccessExpressionDef = defineNode('PropertyAccessExpression', {
  expression: child(),
  name: child<KSIdentifier>(),
});

export const ElementAccessExpressionDef = defineNode('ElementAccessExpression', {
  expression: child(),
  argumentExpression: child(),
});

export const BinaryExpressionDef = defineNode('BinaryExpression', {
  left: child(),
  operatorToken: child(),
  right: child(),
});

export const PrefixUnaryExpressionDef = defineNode('PrefixUnaryExpression', {
  operand: child(),
  operator: prop<number>(),
});

export const PostfixUnaryExpressionDef = defineNode('PostfixUnaryExpression', {
  operand: child(),
  operator: prop<number>(),
});

export const ArrowFunctionDef = defineNode('ArrowFunction', {
  typeParameters: list(),
  parameters: list(),
  type: optChild(),
  body: child(),
  modifiers: list(),
});

export const FunctionExpressionDef = defineNode('FunctionExpression', {
  name: optChild<KSIdentifier>(),
  typeParameters: list(),
  parameters: list(),
  type: optChild(),
  body: child(),
  modifiers: list(),
});

export const ObjectLiteralExpressionDef = defineNode('ObjectLiteralExpression', {
  properties: list(),
});

export const ArrayLiteralExpressionDef = defineNode('ArrayLiteralExpression', {
  elements: list(),
});

export const TemplateExpressionDef = defineNode('TemplateExpression', {
  head: child(),
  templateSpans: list(),
});

export const ConditionalExpressionDef = defineNode('ConditionalExpression', {
  condition: child(),
  whenTrue: child(),
  whenFalse: child(),
});

export const NewExpressionDef = defineNode('NewExpression', {
  expression: child(),
  typeArguments: list(),
  arguments: list(),
});

export const AwaitExpressionDef = defineNode('AwaitExpression', {
  expression: child(),
});

export const SpreadElementDef = defineNode('SpreadElement', {
  expression: child(),
});

export const AsExpressionDef = defineNode('AsExpression', {
  expression: child(),
  type: child(),
});

export const ParenthesizedExpressionDef = defineNode('ParenthesizedExpression', {
  expression: child(),
});

export const TypeReferenceNodeDef = defineNode('TypeReference', {
  typeName: child(),
  typeArguments: list(),
});

export const TypeLiteralNodeDef = defineNode('TypeLiteral', {
  members: list(),
});

export const UnionTypeDef = defineNode('UnionType', {
  types: list(),
});

export const IntersectionTypeDef = defineNode('IntersectionType', {
  types: list(),
});

export const FunctionTypeDef = defineNode('FunctionType', {
  typeParameters: list(),
  parameters: list(),
  type: child(),
});

export const ArrayTypeDef = defineNode('ArrayType', {
  elementType: child(),
});

export const TupleTypeDef = defineNode('TupleType', {
  elements: list(),
});

export const LiteralTypeDef = defineNode('LiteralType', {
  literal: child(),
});

export const ConditionalTypeDef = defineNode('ConditionalType', {
  checkType: child(),
  extendsType: child(),
  trueType: child(),
  falseType: child(),
});

export const MappedTypeDef = defineNode('MappedType', {
  typeParameter: child(),
  nameType: optChild(),
  type: optChild(),
});

export const IndexedAccessTypeDef = defineNode('IndexedAccessType', {
  objectType: child(),
  indexType: child(),
});

export const TypeQueryDef = defineNode('TypeQuery', {
  exprName: child(),
});

export const IdentifierDef = defineNode('Identifier', {
  escapedText: prop<string>(),
});

export const StringLiteralDef = defineNode('StringLiteral', {
  value: prop<string>(),
});

export const NumericLiteralDef = defineNode('NumericLiteral', {
  value: prop<string>(),
});

export const NoSubstitutionTemplateLiteralDef = defineNode('NoSubstitutionTemplateLiteral', {
  value: prop<string>(),
});

export const PropertySignatureDef = defineNode('PropertySignature', {
  name: child(),
  type: optChild(),
  questionToken: optChild(),
  modifiers: list(),
});

export const PropertyDeclarationDef = defineNode('PropertyDeclaration', {
  name: child(),
  type: optChild(),
  initializer: optChild(),
  modifiers: list(),
});

export const MethodDeclarationDef = defineNode('MethodDeclaration', {
  name: child(),
  typeParameters: list(),
  parameters: list(),
  type: optChild(),
  body: optChild(),
  modifiers: list(),
});

export const ConstructorDeclarationDef = defineNode('Constructor', {
  parameters: list(),
  body: optChild(),
  modifiers: list(),
});

export const GetAccessorDeclarationDef = defineNode('GetAccessor', {
  name: child(),
  parameters: list(),
  type: optChild(),
  body: optChild(),
  modifiers: list(),
});

export const SetAccessorDeclarationDef = defineNode('SetAccessor', {
  name: child(),
  parameters: list(),
  body: optChild(),
  modifiers: list(),
});

export const ParameterNodeDef = defineNode('Parameter', {
  name: child(),
  type: optChild(),
  initializer: optChild(),
  dotDotDotToken: optChild(),
  questionToken: optChild(),
  modifiers: list(),
});

export const TypeParameterNodeDef = defineNode('TypeParameter', {
  name: child<KSIdentifier>(),
  constraint: optChild(),
  default: optChild(),
});

export const PropertyAssignmentDef = defineNode('PropertyAssignment', {
  name: child(),
  initializer: child(),
});

export const ShorthandPropertyAssignmentDef = defineNode('ShorthandPropertyAssignment', {
  name: child<KSIdentifier>(),
});

export const ComputedPropertyNameDef = defineNode('ComputedPropertyName', {
  expression: child(),
});

export const HeritageClauseDef = defineNode('HeritageClause', {
  token: prop<number>(),
  types: list(),
});

export const CatchClauseDef = defineNode('CatchClause', {
  variableDeclaration: optChild(),
  block: child(),
});

export const CaseBlockDef = defineNode('CaseBlock', {
  clauses: list(),
});

export const CaseClauseDef = defineNode('CaseClause', {
  expression: child(),
  statements: list(),
});

export const DefaultClauseDef = defineNode('DefaultClause', {
  statements: list(),
});

export const EnumMemberDef = defineNode('EnumMember', {
  name: child(),
  initializer: optChild(),
});

export const BigIntLiteralDef = defineNode('BigIntLiteral', {
  value: prop<string>(),
});

export const RegularExpressionLiteralDef = defineNode('RegularExpressionLiteral', {
  value: prop<string>(),
});

export const TemplateHeadDef = defineNode('TemplateHead', {
  value: prop<string>(),
});

export const TemplateMiddleDef = defineNode('TemplateMiddle', {
  value: prop<string>(),
});

export const TemplateTailDef = defineNode('TemplateTail', {
  value: prop<string>(),
});

export const JsxTextDef = defineNode('JsxText', {
  value: prop<string>(),
  containsOnlyTriviaWhiteSpaces: prop<boolean>(),
});

export const PrivateIdentifierDef = defineNode('PrivateIdentifier', {
  escapedText: prop<string>(),
});

export const QualifiedNameDef = defineNode('QualifiedName', {
  left: child(),
  right: child(),
});

export const DecoratorDef = defineNode('Decorator', {
  expression: child(),
});

export const MethodSignatureDef = defineNode('MethodSignature', {
  name: child(),
  typeParameters: list(),
  parameters: list(),
  type: optChild(),
  modifiers: list(),
});

export const ClassStaticBlockDeclarationDef = defineNode('ClassStaticBlockDeclaration', {
  body: child(),
  modifiers: list(),
});

export const CallSignatureDef = defineNode('CallSignature', {
  typeParameters: list(),
  parameters: list(),
  type: optChild(),
});

export const ConstructSignatureDef = defineNode('ConstructSignature', {
  typeParameters: list(),
  parameters: list(),
  type: optChild(),
});

export const IndexSignatureDef = defineNode('IndexSignature', {
  parameters: list(),
  type: optChild(),
  modifiers: list(),
});

export const TypePredicateDef = defineNode('TypePredicate', {
  parameterName: child(),
  type: optChild(),
});

export const ConstructorTypeDef = defineNode('ConstructorType', {
  typeParameters: list(),
  parameters: list(),
  type: child(),
  modifiers: list(),
});

export const OptionalTypeDef = defineNode('OptionalType', {
  type: child(),
});

export const RestTypeDef = defineNode('RestType', {
  type: child(),
});

export const InferTypeDef = defineNode('InferType', {
  typeParameter: child(),
});

export const ParenthesizedTypeDef = defineNode('ParenthesizedType', {
  type: child(),
});

export const TypeOperatorDef = defineNode('TypeOperator', {
  type: child(),
  operator: prop<number>(),
});

export const NamedTupleMemberDef = defineNode('NamedTupleMember', {
  name: child(),
  type: child(),
  dotDotDotToken: optChild(),
  questionToken: optChild(),
});

export const TemplateLiteralTypeDef = defineNode('TemplateLiteralType', {
  head: child(),
  templateSpans: list(),
});

export const TemplateLiteralTypeSpanDef = defineNode('TemplateLiteralTypeSpan', {
  type: child(),
  literal: child(),
});

export const ImportTypeDef = defineNode('ImportType', {
  argument: child(),
  qualifier: optChild(),
  typeArguments: list(),
  isTypeOf: prop<boolean>(),
});

export const ObjectBindingPatternDef = defineNode('ObjectBindingPattern', {
  elements: list(),
});

export const ArrayBindingPatternDef = defineNode('ArrayBindingPattern', {
  elements: list(),
});

export const BindingElementDef = defineNode('BindingElement', {
  name: child(),
  propertyName: optChild(),
  initializer: optChild(),
  dotDotDotToken: optChild(),
});

export const TaggedTemplateExpressionDef = defineNode('TaggedTemplateExpression', {
  tag: child(),
  typeArguments: list(),
  template: child(),
});

export const TypeAssertionExpressionDef = defineNode('TypeAssertionExpression', {
  type: child(),
  expression: child(),
});

export const DeleteExpressionDef = defineNode('DeleteExpression', {
  expression: child(),
});

export const TypeOfExpressionDef = defineNode('TypeOfExpression', {
  expression: child(),
});

export const VoidExpressionDef = defineNode('VoidExpression', {
  expression: child(),
});

export const YieldExpressionDef = defineNode('YieldExpression', {
  expression: optChild(),
  asteriskToken: optChild(),
});

export const ClassExpressionDef = defineNode('ClassExpression', {
  name: optChild<KSIdentifier>(),
  typeParameters: list(),
  members: list(),
  heritageClauses: list(),
  modifiers: list(),
});

export const ExpressionWithTypeArgumentsDef = defineNode('ExpressionWithTypeArguments', {
  expression: child(),
  typeArguments: list(),
});

export const NonNullExpressionDef = defineNode('NonNullExpression', {
  expression: child(),
});

export const MetaPropertyDef = defineNode('MetaProperty', {
  name: child(),
  keywordToken: prop<number>(),
});

export const SatisfiesExpressionDef = defineNode('SatisfiesExpression', {
  expression: child(),
  type: child(),
});

export const TemplateSpanDef = defineNode('TemplateSpan', {
  expression: child(),
  literal: child(),
});

export const ContinueStatementDef = defineNode('ContinueStatement', {
  label: optChild(),
});

export const BreakStatementDef = defineNode('BreakStatement', {
  label: optChild(),
});

export const WithStatementDef = defineNode('WithStatement', {
  expression: child(),
  statement: child(),
});

export const LabeledStatementDef = defineNode('LabeledStatement', {
  label: child(),
  statement: child(),
});

export const ModuleDeclarationDef = defineNode('ModuleDeclaration', {
  name: child(),
  body: optChild(),
  modifiers: list(),
});

export const ModuleBlockDef = defineNode('ModuleBlock', {
  statements: list(),
});

export const NamespaceExportDeclarationDef = defineNode('NamespaceExportDeclaration', {
  name: child(),
});

export const ImportEqualsDeclarationDef = defineNode('ImportEqualsDeclaration', {
  name: child(),
  moduleReference: child(),
  modifiers: list(),
  isTypeOnly: prop<boolean>(),
});

export const NamedExportsDef = defineNode('NamedExports', {
  elements: list(),
});

export const NamespaceExportDef = defineNode('NamespaceExport', {
  name: child(),
});

export const ExportSpecifierDef = defineNode('ExportSpecifier', {
  name: child(),
  propertyName: optChild(),
  isTypeOnly: prop<boolean>(),
});

export const ExternalModuleReferenceDef = defineNode('ExternalModuleReference', {
  expression: child(),
});

export const JsxElementDef = defineNode('JsxElement', {
  openingElement: child(),
  closingElement: child(),
});

export const JsxSelfClosingElementDef = defineNode('JsxSelfClosingElement', {
  tagName: child(),
  typeArguments: list(),
  attributes: child(),
});

export const JsxOpeningElementDef = defineNode('JsxOpeningElement', {
  tagName: child(),
  typeArguments: list(),
  attributes: child(),
});

export const JsxClosingElementDef = defineNode('JsxClosingElement', {
  tagName: child(),
});

export const JsxFragmentDef = defineNode('JsxFragment', {
  openingFragment: child(),
  closingFragment: child(),
});

export const JsxAttributeDef = defineNode('JsxAttribute', {
  name: child(),
  initializer: optChild(),
});

export const JsxAttributesDef = defineNode('JsxAttributes', {
  properties: list(),
});

export const JsxSpreadAttributeDef = defineNode('JsxSpreadAttribute', {
  expression: child(),
});

export const JsxExpressionDef = defineNode('JsxExpression', {
  expression: optChild(),
});

export const JsxNamespacedNameDef = defineNode('JsxNamespacedName', {
  namespace: child(),
  name: child(),
});

export const ImportAttributesDef = defineNode('ImportAttributes', {
  elements: list(),
});

export const ImportAttributeDef = defineNode('ImportAttribute', {
  name: child(),
  value: child(),
});

export const SpreadAssignmentDef = defineNode('SpreadAssignment', {
  expression: child(),
});

export const JSDocTypeExpressionDef = defineNode('JSDocTypeExpression', {
  type: child(),
});

export const JSDocNameReferenceDef = defineNode('JSDocNameReference', {
  name: child(),
});

export const JSDocMemberNameDef = defineNode('JSDocMemberName', {
  left: child(),
  right: child(),
});

export const JSDocNullableTypeDef = defineNode('JSDocNullableType', {
  type: child(),
});

export const JSDocNonNullableTypeDef = defineNode('JSDocNonNullableType', {
  type: child(),
});

export const JSDocOptionalTypeDef = defineNode('JSDocOptionalType', {
  type: child(),
});

export const JSDocFunctionTypeDef = defineNode('JSDocFunctionType', {
  parameters: list(),
  type: optChild(),
});

export const JSDocVariadicTypeDef = defineNode('JSDocVariadicType', {
  type: child(),
});

export const JSDocTypeLiteralDef = defineNode('JSDocTypeLiteral', {
  isArrayType: prop<boolean>(),
});

export const PartiallyEmittedExpressionDef = defineNode('PartiallyEmittedExpression', {
  expression: child(),
});

export const CommaListExpressionDef = defineNode('CommaListExpression', {
  elements: list(),
});

export const MissingDeclarationDef = defineNode('MissingDeclaration', {
  modifiers: list(),
});

// ═══════════════════════════════════════════════════════════════════════
// Leaf node definitions (tokens, keywords, trivia, simple nodes)
// ═══════════════════════════════════════════════════════════════════════

export const UnknownDef = defineLeaf('Unknown');
export const EndOfFileTokenDef = defineLeaf('EndOfFileToken');
export const SingleLineCommentTriviaDef = defineLeaf('SingleLineCommentTrivia');
export const MultiLineCommentTriviaDef = defineLeaf('MultiLineCommentTrivia');
export const NewLineTriviaDef = defineLeaf('NewLineTrivia');
export const WhitespaceTriviaDef = defineLeaf('WhitespaceTrivia');
export const ShebangTriviaDef = defineLeaf('ShebangTrivia');
export const ConflictMarkerTriviaDef = defineLeaf('ConflictMarkerTrivia');
export const NonTextFileMarkerTriviaDef = defineLeaf('NonTextFileMarkerTrivia');
export const JsxTextAllWhiteSpacesDef = defineLeaf('JsxTextAllWhiteSpaces');
export const OpenBraceTokenDef = defineLeaf('OpenBraceToken');
export const CloseBraceTokenDef = defineLeaf('CloseBraceToken');
export const OpenParenTokenDef = defineLeaf('OpenParenToken');
export const CloseParenTokenDef = defineLeaf('CloseParenToken');
export const OpenBracketTokenDef = defineLeaf('OpenBracketToken');
export const CloseBracketTokenDef = defineLeaf('CloseBracketToken');
export const DotTokenDef = defineLeaf('DotToken');
export const DotDotDotTokenDef = defineLeaf('DotDotDotToken');
export const SemicolonTokenDef = defineLeaf('SemicolonToken');
export const CommaTokenDef = defineLeaf('CommaToken');
export const QuestionDotTokenDef = defineLeaf('QuestionDotToken');
export const LessThanTokenDef = defineLeaf('LessThanToken');
export const LessThanSlashTokenDef = defineLeaf('LessThanSlashToken');
export const GreaterThanTokenDef = defineLeaf('GreaterThanToken');
export const LessThanEqualsTokenDef = defineLeaf('LessThanEqualsToken');
export const GreaterThanEqualsTokenDef = defineLeaf('GreaterThanEqualsToken');
export const EqualsEqualsTokenDef = defineLeaf('EqualsEqualsToken');
export const ExclamationEqualsTokenDef = defineLeaf('ExclamationEqualsToken');
export const EqualsEqualsEqualsTokenDef = defineLeaf('EqualsEqualsEqualsToken');
export const ExclamationEqualsEqualsTokenDef = defineLeaf('ExclamationEqualsEqualsToken');
export const EqualsGreaterThanTokenDef = defineLeaf('EqualsGreaterThanToken');
export const PlusTokenDef = defineLeaf('PlusToken');
export const MinusTokenDef = defineLeaf('MinusToken');
export const AsteriskTokenDef = defineLeaf('AsteriskToken');
export const AsteriskAsteriskTokenDef = defineLeaf('AsteriskAsteriskToken');
export const SlashTokenDef = defineLeaf('SlashToken');
export const PercentTokenDef = defineLeaf('PercentToken');
export const PlusPlusTokenDef = defineLeaf('PlusPlusToken');
export const MinusMinusTokenDef = defineLeaf('MinusMinusToken');
export const LessThanLessThanTokenDef = defineLeaf('LessThanLessThanToken');
export const GreaterThanGreaterThanTokenDef = defineLeaf('GreaterThanGreaterThanToken');
export const GreaterThanGreaterThanGreaterThanTokenDef = defineLeaf('GreaterThanGreaterThanGreaterThanToken');
export const AmpersandTokenDef = defineLeaf('AmpersandToken');
export const BarTokenDef = defineLeaf('BarToken');
export const CaretTokenDef = defineLeaf('CaretToken');
export const ExclamationTokenDef = defineLeaf('ExclamationToken');
export const TildeTokenDef = defineLeaf('TildeToken');
export const AmpersandAmpersandTokenDef = defineLeaf('AmpersandAmpersandToken');
export const BarBarTokenDef = defineLeaf('BarBarToken');
export const QuestionTokenDef = defineLeaf('QuestionToken');
export const ColonTokenDef = defineLeaf('ColonToken');
export const AtTokenDef = defineLeaf('AtToken');
export const QuestionQuestionTokenDef = defineLeaf('QuestionQuestionToken');
export const BacktickTokenDef = defineLeaf('BacktickToken');
export const HashTokenDef = defineLeaf('HashToken');
export const EqualsTokenDef = defineLeaf('EqualsToken');
export const PlusEqualsTokenDef = defineLeaf('PlusEqualsToken');
export const MinusEqualsTokenDef = defineLeaf('MinusEqualsToken');
export const AsteriskEqualsTokenDef = defineLeaf('AsteriskEqualsToken');
export const AsteriskAsteriskEqualsTokenDef = defineLeaf('AsteriskAsteriskEqualsToken');
export const SlashEqualsTokenDef = defineLeaf('SlashEqualsToken');
export const PercentEqualsTokenDef = defineLeaf('PercentEqualsToken');
export const LessThanLessThanEqualsTokenDef = defineLeaf('LessThanLessThanEqualsToken');
export const GreaterThanGreaterThanEqualsTokenDef = defineLeaf('GreaterThanGreaterThanEqualsToken');
export const GreaterThanGreaterThanGreaterThanEqualsTokenDef = defineLeaf('GreaterThanGreaterThanGreaterThanEqualsToken');
export const AmpersandEqualsTokenDef = defineLeaf('AmpersandEqualsToken');
export const BarEqualsTokenDef = defineLeaf('BarEqualsToken');
export const BarBarEqualsTokenDef = defineLeaf('BarBarEqualsToken');
export const AmpersandAmpersandEqualsTokenDef = defineLeaf('AmpersandAmpersandEqualsToken');
export const QuestionQuestionEqualsTokenDef = defineLeaf('QuestionQuestionEqualsToken');
export const CaretEqualsTokenDef = defineLeaf('CaretEqualsToken');
export const JSDocCommentTextTokenDef = defineLeaf('JSDocCommentTextToken');
export const BreakKeywordDef = defineLeaf('BreakKeyword');
export const CaseKeywordDef = defineLeaf('CaseKeyword');
export const CatchKeywordDef = defineLeaf('CatchKeyword');
export const ClassKeywordDef = defineLeaf('ClassKeyword');
export const ConstKeywordDef = defineLeaf('ConstKeyword');
export const ContinueKeywordDef = defineLeaf('ContinueKeyword');
export const DebuggerKeywordDef = defineLeaf('DebuggerKeyword');
export const DefaultKeywordDef = defineLeaf('DefaultKeyword');
export const DeleteKeywordDef = defineLeaf('DeleteKeyword');
export const DoKeywordDef = defineLeaf('DoKeyword');
export const ElseKeywordDef = defineLeaf('ElseKeyword');
export const EnumKeywordDef = defineLeaf('EnumKeyword');
export const ExportKeywordDef = defineLeaf('ExportKeyword');
export const ExtendsKeywordDef = defineLeaf('ExtendsKeyword');
export const FalseKeywordDef = defineLeaf('FalseKeyword');
export const FinallyKeywordDef = defineLeaf('FinallyKeyword');
export const ForKeywordDef = defineLeaf('ForKeyword');
export const FunctionKeywordDef = defineLeaf('FunctionKeyword');
export const IfKeywordDef = defineLeaf('IfKeyword');
export const ImportKeywordDef = defineLeaf('ImportKeyword');
export const InKeywordDef = defineLeaf('InKeyword');
export const InstanceOfKeywordDef = defineLeaf('InstanceOfKeyword');
export const NewKeywordDef = defineLeaf('NewKeyword');
export const NullKeywordDef = defineLeaf('NullKeyword');
export const ReturnKeywordDef = defineLeaf('ReturnKeyword');
export const SuperKeywordDef = defineLeaf('SuperKeyword');
export const SwitchKeywordDef = defineLeaf('SwitchKeyword');
export const ThisKeywordDef = defineLeaf('ThisKeyword');
export const ThrowKeywordDef = defineLeaf('ThrowKeyword');
export const TrueKeywordDef = defineLeaf('TrueKeyword');
export const TryKeywordDef = defineLeaf('TryKeyword');
export const TypeOfKeywordDef = defineLeaf('TypeOfKeyword');
export const VarKeywordDef = defineLeaf('VarKeyword');
export const VoidKeywordDef = defineLeaf('VoidKeyword');
export const WhileKeywordDef = defineLeaf('WhileKeyword');
export const WithKeywordDef = defineLeaf('WithKeyword');
export const ImplementsKeywordDef = defineLeaf('ImplementsKeyword');
export const InterfaceKeywordDef = defineLeaf('InterfaceKeyword');
export const LetKeywordDef = defineLeaf('LetKeyword');
export const PackageKeywordDef = defineLeaf('PackageKeyword');
export const PrivateKeywordDef = defineLeaf('PrivateKeyword');
export const ProtectedKeywordDef = defineLeaf('ProtectedKeyword');
export const PublicKeywordDef = defineLeaf('PublicKeyword');
export const StaticKeywordDef = defineLeaf('StaticKeyword');
export const YieldKeywordDef = defineLeaf('YieldKeyword');
export const AbstractKeywordDef = defineLeaf('AbstractKeyword');
export const AccessorKeywordDef = defineLeaf('AccessorKeyword');
export const AsKeywordDef = defineLeaf('AsKeyword');
export const AssertsKeywordDef = defineLeaf('AssertsKeyword');
export const AssertKeywordDef = defineLeaf('AssertKeyword');
export const AnyKeywordDef = defineLeaf('AnyKeyword');
export const AsyncKeywordDef = defineLeaf('AsyncKeyword');
export const AwaitKeywordDef = defineLeaf('AwaitKeyword');
export const BooleanKeywordDef = defineLeaf('BooleanKeyword');
export const ConstructorKeywordDef = defineLeaf('ConstructorKeyword');
export const DeclareKeywordDef = defineLeaf('DeclareKeyword');
export const GetKeywordDef = defineLeaf('GetKeyword');
export const InferKeywordDef = defineLeaf('InferKeyword');
export const IntrinsicKeywordDef = defineLeaf('IntrinsicKeyword');
export const IsKeywordDef = defineLeaf('IsKeyword');
export const KeyOfKeywordDef = defineLeaf('KeyOfKeyword');
export const ModuleKeywordDef = defineLeaf('ModuleKeyword');
export const NamespaceKeywordDef = defineLeaf('NamespaceKeyword');
export const NeverKeywordDef = defineLeaf('NeverKeyword');
export const OutKeywordDef = defineLeaf('OutKeyword');
export const ReadonlyKeywordDef = defineLeaf('ReadonlyKeyword');
export const RequireKeywordDef = defineLeaf('RequireKeyword');
export const NumberKeywordDef = defineLeaf('NumberKeyword');
export const ObjectKeywordDef = defineLeaf('ObjectKeyword');
export const SatisfiesKeywordDef = defineLeaf('SatisfiesKeyword');
export const SetKeywordDef = defineLeaf('SetKeyword');
export const StringKeywordDef = defineLeaf('StringKeyword');
export const SymbolKeywordDef = defineLeaf('SymbolKeyword');
export const TypeKeywordDef = defineLeaf('TypeKeyword');
export const UndefinedKeywordDef = defineLeaf('UndefinedKeyword');
export const UniqueKeywordDef = defineLeaf('UniqueKeyword');
export const UnknownKeywordDef = defineLeaf('UnknownKeyword');
export const UsingKeywordDef = defineLeaf('UsingKeyword');
export const FromKeywordDef = defineLeaf('FromKeyword');
export const GlobalKeywordDef = defineLeaf('GlobalKeyword');
export const BigIntKeywordDef = defineLeaf('BigIntKeyword');
export const OverrideKeywordDef = defineLeaf('OverrideKeyword');
export const OfKeywordDef = defineLeaf('OfKeyword');
export const DeferKeywordDef = defineLeaf('DeferKeyword');
export const JSDocAllTypeDef = defineLeaf('JSDocAllType');
export const JSDocUnknownTypeDef = defineLeaf('JSDocUnknownType');
export const JSDocNamepathTypeDef = defineLeaf('JSDocNamepathType');
export const JSDocDef = defineLeaf('JSDoc');
export const JSDocTextDef = defineLeaf('JSDocText');
export const JSDocSignatureDef = defineLeaf('JSDocSignature');
export const JSDocLinkDef = defineLeaf('JSDocLink');
export const JSDocLinkCodeDef = defineLeaf('JSDocLinkCode');
export const JSDocLinkPlainDef = defineLeaf('JSDocLinkPlain');
export const JSDocTagDef = defineLeaf('JSDocTag');
export const JSDocAugmentsTagDef = defineLeaf('JSDocAugmentsTag');
export const JSDocImplementsTagDef = defineLeaf('JSDocImplementsTag');
export const JSDocAuthorTagDef = defineLeaf('JSDocAuthorTag');
export const JSDocDeprecatedTagDef = defineLeaf('JSDocDeprecatedTag');
export const JSDocClassTagDef = defineLeaf('JSDocClassTag');
export const JSDocPublicTagDef = defineLeaf('JSDocPublicTag');
export const JSDocPrivateTagDef = defineLeaf('JSDocPrivateTag');
export const JSDocProtectedTagDef = defineLeaf('JSDocProtectedTag');
export const JSDocReadonlyTagDef = defineLeaf('JSDocReadonlyTag');
export const JSDocOverrideTagDef = defineLeaf('JSDocOverrideTag');
export const JSDocCallbackTagDef = defineLeaf('JSDocCallbackTag');
export const JSDocOverloadTagDef = defineLeaf('JSDocOverloadTag');
export const JSDocEnumTagDef = defineLeaf('JSDocEnumTag');
export const JSDocParameterTagDef = defineLeaf('JSDocParameterTag');
export const JSDocReturnTagDef = defineLeaf('JSDocReturnTag');
export const JSDocThisTagDef = defineLeaf('JSDocThisTag');
export const JSDocTypeTagDef = defineLeaf('JSDocTypeTag');
export const JSDocTemplateTagDef = defineLeaf('JSDocTemplateTag');
export const JSDocTypedefTagDef = defineLeaf('JSDocTypedefTag');
export const JSDocSeeTagDef = defineLeaf('JSDocSeeTag');
export const JSDocPropertyTagDef = defineLeaf('JSDocPropertyTag');
export const JSDocThrowsTagDef = defineLeaf('JSDocThrowsTag');
export const JSDocSatisfiesTagDef = defineLeaf('JSDocSatisfiesTag');
export const JSDocImportTagDef = defineLeaf('JSDocImportTag');
export const SyntaxListDef = defineLeaf('SyntaxList');
export const NotEmittedStatementDef = defineLeaf('NotEmittedStatement');
export const NotEmittedTypeElementDef = defineLeaf('NotEmittedTypeElement');
export const SyntheticExpressionDef = defineLeaf('SyntheticExpression');
export const SyntheticReferenceExpressionDef = defineLeaf('SyntheticReferenceExpression');
export const BundleDef = defineLeaf('Bundle');
export const ImportTypeAssertionContainerDef = defineLeaf('ImportTypeAssertionContainer');
export const ThisTypeDef = defineLeaf('ThisType');
export const OmittedExpressionDef = defineLeaf('OmittedExpression');
export const SemicolonClassElementDef = defineLeaf('SemicolonClassElement');
export const EmptyStatementDef = defineLeaf('EmptyStatement');
export const DebuggerStatementDef = defineLeaf('DebuggerStatement');
export const JsxOpeningFragmentDef = defineLeaf('JsxOpeningFragment');
export const JsxClosingFragmentDef = defineLeaf('JsxClosingFragment');

// ═══════════════════════════════════════════════════════════════════════
// Inferred TypeScript types
// ═══════════════════════════════════════════════════════════════════════

export type KSProgram = InferNode<typeof ProgramDef>;
export type KSCompilationUnit = InferNode<typeof CompilationUnitDef>;
export type KSTypeAliasDeclaration = InferNode<typeof TypeAliasDeclarationDef>;
export type KSInterfaceDeclaration = InferNode<typeof InterfaceDeclarationDef>;
export type KSFunctionDeclaration = InferNode<typeof FunctionDeclarationDef>;
export type KSClassDeclaration = InferNode<typeof ClassDeclarationDef>;
export type KSEnumDeclaration = InferNode<typeof EnumDeclarationDef>;
export type KSVariableStatement = InferNode<typeof VariableStatementDef>;
export type KSVariableDeclarationList = InferNode<typeof VariableDeclarationListDef>;
export type KSVariableDeclaration = InferNode<typeof VariableDeclarationDef>;
export type KSImportDeclaration = InferNode<typeof ImportDeclarationDef>;
export type KSImportClause = InferNode<typeof ImportClauseDef>;
export type KSNamedImports = InferNode<typeof NamedImportsDef>;
export type KSImportSpecifier = InferNode<typeof ImportSpecifierDef>;
export type KSNamespaceImport = InferNode<typeof NamespaceImportDef>;
export type KSExportDeclaration = InferNode<typeof ExportDeclarationDef>;
export type KSExportAssignment = InferNode<typeof ExportAssignmentDef>;
export type KSBlock = InferNode<typeof BlockDef>;
export type KSExpressionStatement = InferNode<typeof ExpressionStatementDef>;
export type KSReturnStatement = InferNode<typeof ReturnStatementDef>;
export type KSIfStatement = InferNode<typeof IfStatementDef>;
export type KSForStatement = InferNode<typeof ForStatementDef>;
export type KSForOfStatement = InferNode<typeof ForOfStatementDef>;
export type KSForInStatement = InferNode<typeof ForInStatementDef>;
export type KSWhileStatement = InferNode<typeof WhileStatementDef>;
export type KSDoStatement = InferNode<typeof DoStatementDef>;
export type KSSwitchStatement = InferNode<typeof SwitchStatementDef>;
export type KSThrowStatement = InferNode<typeof ThrowStatementDef>;
export type KSTryStatement = InferNode<typeof TryStatementDef>;
export type KSCallExpression = InferNode<typeof CallExpressionDef>;
export type KSPropertyAccessExpression = InferNode<typeof PropertyAccessExpressionDef>;
export type KSElementAccessExpression = InferNode<typeof ElementAccessExpressionDef>;
export type KSBinaryExpression = InferNode<typeof BinaryExpressionDef>;
export type KSPrefixUnaryExpression = InferNode<typeof PrefixUnaryExpressionDef>;
export type KSPostfixUnaryExpression = InferNode<typeof PostfixUnaryExpressionDef>;
export type KSArrowFunction = InferNode<typeof ArrowFunctionDef>;
export type KSFunctionExpression = InferNode<typeof FunctionExpressionDef>;
export type KSObjectLiteralExpression = InferNode<typeof ObjectLiteralExpressionDef>;
export type KSArrayLiteralExpression = InferNode<typeof ArrayLiteralExpressionDef>;
export type KSTemplateExpression = InferNode<typeof TemplateExpressionDef>;
export type KSConditionalExpression = InferNode<typeof ConditionalExpressionDef>;
export type KSNewExpression = InferNode<typeof NewExpressionDef>;
export type KSAwaitExpression = InferNode<typeof AwaitExpressionDef>;
export type KSSpreadElement = InferNode<typeof SpreadElementDef>;
export type KSAsExpression = InferNode<typeof AsExpressionDef>;
export type KSParenthesizedExpression = InferNode<typeof ParenthesizedExpressionDef>;
export type KSTypeReferenceNode = InferNode<typeof TypeReferenceNodeDef>;
export type KSTypeLiteralNode = InferNode<typeof TypeLiteralNodeDef>;
export type KSUnionType = InferNode<typeof UnionTypeDef>;
export type KSIntersectionType = InferNode<typeof IntersectionTypeDef>;
export type KSFunctionType = InferNode<typeof FunctionTypeDef>;
export type KSArrayType = InferNode<typeof ArrayTypeDef>;
export type KSTupleType = InferNode<typeof TupleTypeDef>;
export type KSLiteralType = InferNode<typeof LiteralTypeDef>;
export type KSConditionalType = InferNode<typeof ConditionalTypeDef>;
export type KSMappedType = InferNode<typeof MappedTypeDef>;
export type KSIndexedAccessType = InferNode<typeof IndexedAccessTypeDef>;
export type KSTypeQuery = InferNode<typeof TypeQueryDef>;
export type KSIdentifier = InferNode<typeof IdentifierDef>;
export type KSStringLiteral = InferNode<typeof StringLiteralDef>;
export type KSNumericLiteral = InferNode<typeof NumericLiteralDef>;
export type KSNoSubstitutionTemplateLiteral = InferNode<typeof NoSubstitutionTemplateLiteralDef>;
export type KSPropertySignature = InferNode<typeof PropertySignatureDef>;
export type KSPropertyDeclaration = InferNode<typeof PropertyDeclarationDef>;
export type KSMethodDeclaration = InferNode<typeof MethodDeclarationDef>;
export type KSConstructorDeclaration = InferNode<typeof ConstructorDeclarationDef>;
export type KSGetAccessorDeclaration = InferNode<typeof GetAccessorDeclarationDef>;
export type KSSetAccessorDeclaration = InferNode<typeof SetAccessorDeclarationDef>;
export type KSParameterNode = InferNode<typeof ParameterNodeDef>;
export type KSTypeParameterNode = InferNode<typeof TypeParameterNodeDef>;
export type KSPropertyAssignment = InferNode<typeof PropertyAssignmentDef>;
export type KSShorthandPropertyAssignment = InferNode<typeof ShorthandPropertyAssignmentDef>;
export type KSComputedPropertyName = InferNode<typeof ComputedPropertyNameDef>;
export type KSHeritageClause = InferNode<typeof HeritageClauseDef>;
export type KSCatchClause = InferNode<typeof CatchClauseDef>;
export type KSCaseBlock = InferNode<typeof CaseBlockDef>;
export type KSCaseClause = InferNode<typeof CaseClauseDef>;
export type KSDefaultClause = InferNode<typeof DefaultClauseDef>;
export type KSEnumMember = InferNode<typeof EnumMemberDef>;
export type KSUnknown = InferNode<typeof UnknownDef>;
export type KSEndOfFileToken = InferNode<typeof EndOfFileTokenDef>;
export type KSSingleLineCommentTrivia = InferNode<typeof SingleLineCommentTriviaDef>;
export type KSMultiLineCommentTrivia = InferNode<typeof MultiLineCommentTriviaDef>;
export type KSNewLineTrivia = InferNode<typeof NewLineTriviaDef>;
export type KSWhitespaceTrivia = InferNode<typeof WhitespaceTriviaDef>;
export type KSShebangTrivia = InferNode<typeof ShebangTriviaDef>;
export type KSConflictMarkerTrivia = InferNode<typeof ConflictMarkerTriviaDef>;
export type KSNonTextFileMarkerTrivia = InferNode<typeof NonTextFileMarkerTriviaDef>;
export type KSJsxTextAllWhiteSpaces = InferNode<typeof JsxTextAllWhiteSpacesDef>;
export type KSOpenBraceToken = InferNode<typeof OpenBraceTokenDef>;
export type KSCloseBraceToken = InferNode<typeof CloseBraceTokenDef>;
export type KSOpenParenToken = InferNode<typeof OpenParenTokenDef>;
export type KSCloseParenToken = InferNode<typeof CloseParenTokenDef>;
export type KSOpenBracketToken = InferNode<typeof OpenBracketTokenDef>;
export type KSCloseBracketToken = InferNode<typeof CloseBracketTokenDef>;
export type KSDotToken = InferNode<typeof DotTokenDef>;
export type KSDotDotDotToken = InferNode<typeof DotDotDotTokenDef>;
export type KSSemicolonToken = InferNode<typeof SemicolonTokenDef>;
export type KSCommaToken = InferNode<typeof CommaTokenDef>;
export type KSQuestionDotToken = InferNode<typeof QuestionDotTokenDef>;
export type KSLessThanToken = InferNode<typeof LessThanTokenDef>;
export type KSLessThanSlashToken = InferNode<typeof LessThanSlashTokenDef>;
export type KSGreaterThanToken = InferNode<typeof GreaterThanTokenDef>;
export type KSLessThanEqualsToken = InferNode<typeof LessThanEqualsTokenDef>;
export type KSGreaterThanEqualsToken = InferNode<typeof GreaterThanEqualsTokenDef>;
export type KSEqualsEqualsToken = InferNode<typeof EqualsEqualsTokenDef>;
export type KSExclamationEqualsToken = InferNode<typeof ExclamationEqualsTokenDef>;
export type KSEqualsEqualsEqualsToken = InferNode<typeof EqualsEqualsEqualsTokenDef>;
export type KSExclamationEqualsEqualsToken = InferNode<typeof ExclamationEqualsEqualsTokenDef>;
export type KSEqualsGreaterThanToken = InferNode<typeof EqualsGreaterThanTokenDef>;
export type KSPlusToken = InferNode<typeof PlusTokenDef>;
export type KSMinusToken = InferNode<typeof MinusTokenDef>;
export type KSAsteriskToken = InferNode<typeof AsteriskTokenDef>;
export type KSAsteriskAsteriskToken = InferNode<typeof AsteriskAsteriskTokenDef>;
export type KSSlashToken = InferNode<typeof SlashTokenDef>;
export type KSPercentToken = InferNode<typeof PercentTokenDef>;
export type KSPlusPlusToken = InferNode<typeof PlusPlusTokenDef>;
export type KSMinusMinusToken = InferNode<typeof MinusMinusTokenDef>;
export type KSLessThanLessThanToken = InferNode<typeof LessThanLessThanTokenDef>;
export type KSGreaterThanGreaterThanToken = InferNode<typeof GreaterThanGreaterThanTokenDef>;
export type KSGreaterThanGreaterThanGreaterThanToken = InferNode<typeof GreaterThanGreaterThanGreaterThanTokenDef>;
export type KSAmpersandToken = InferNode<typeof AmpersandTokenDef>;
export type KSBarToken = InferNode<typeof BarTokenDef>;
export type KSCaretToken = InferNode<typeof CaretTokenDef>;
export type KSExclamationToken = InferNode<typeof ExclamationTokenDef>;
export type KSTildeToken = InferNode<typeof TildeTokenDef>;
export type KSAmpersandAmpersandToken = InferNode<typeof AmpersandAmpersandTokenDef>;
export type KSBarBarToken = InferNode<typeof BarBarTokenDef>;
export type KSQuestionToken = InferNode<typeof QuestionTokenDef>;
export type KSColonToken = InferNode<typeof ColonTokenDef>;
export type KSAtToken = InferNode<typeof AtTokenDef>;
export type KSQuestionQuestionToken = InferNode<typeof QuestionQuestionTokenDef>;
export type KSBacktickToken = InferNode<typeof BacktickTokenDef>;
export type KSHashToken = InferNode<typeof HashTokenDef>;
export type KSEqualsToken = InferNode<typeof EqualsTokenDef>;
export type KSPlusEqualsToken = InferNode<typeof PlusEqualsTokenDef>;
export type KSMinusEqualsToken = InferNode<typeof MinusEqualsTokenDef>;
export type KSAsteriskEqualsToken = InferNode<typeof AsteriskEqualsTokenDef>;
export type KSAsteriskAsteriskEqualsToken = InferNode<typeof AsteriskAsteriskEqualsTokenDef>;
export type KSSlashEqualsToken = InferNode<typeof SlashEqualsTokenDef>;
export type KSPercentEqualsToken = InferNode<typeof PercentEqualsTokenDef>;
export type KSLessThanLessThanEqualsToken = InferNode<typeof LessThanLessThanEqualsTokenDef>;
export type KSGreaterThanGreaterThanEqualsToken = InferNode<typeof GreaterThanGreaterThanEqualsTokenDef>;
export type KSGreaterThanGreaterThanGreaterThanEqualsToken = InferNode<typeof GreaterThanGreaterThanGreaterThanEqualsTokenDef>;
export type KSAmpersandEqualsToken = InferNode<typeof AmpersandEqualsTokenDef>;
export type KSBarEqualsToken = InferNode<typeof BarEqualsTokenDef>;
export type KSBarBarEqualsToken = InferNode<typeof BarBarEqualsTokenDef>;
export type KSAmpersandAmpersandEqualsToken = InferNode<typeof AmpersandAmpersandEqualsTokenDef>;
export type KSQuestionQuestionEqualsToken = InferNode<typeof QuestionQuestionEqualsTokenDef>;
export type KSCaretEqualsToken = InferNode<typeof CaretEqualsTokenDef>;
export type KSJSDocCommentTextToken = InferNode<typeof JSDocCommentTextTokenDef>;
export type KSBreakKeyword = InferNode<typeof BreakKeywordDef>;
export type KSCaseKeyword = InferNode<typeof CaseKeywordDef>;
export type KSCatchKeyword = InferNode<typeof CatchKeywordDef>;
export type KSClassKeyword = InferNode<typeof ClassKeywordDef>;
export type KSConstKeyword = InferNode<typeof ConstKeywordDef>;
export type KSContinueKeyword = InferNode<typeof ContinueKeywordDef>;
export type KSDebuggerKeyword = InferNode<typeof DebuggerKeywordDef>;
export type KSDefaultKeyword = InferNode<typeof DefaultKeywordDef>;
export type KSDeleteKeyword = InferNode<typeof DeleteKeywordDef>;
export type KSDoKeyword = InferNode<typeof DoKeywordDef>;
export type KSElseKeyword = InferNode<typeof ElseKeywordDef>;
export type KSEnumKeyword = InferNode<typeof EnumKeywordDef>;
export type KSExportKeyword = InferNode<typeof ExportKeywordDef>;
export type KSExtendsKeyword = InferNode<typeof ExtendsKeywordDef>;
export type KSFalseKeyword = InferNode<typeof FalseKeywordDef>;
export type KSFinallyKeyword = InferNode<typeof FinallyKeywordDef>;
export type KSForKeyword = InferNode<typeof ForKeywordDef>;
export type KSFunctionKeyword = InferNode<typeof FunctionKeywordDef>;
export type KSIfKeyword = InferNode<typeof IfKeywordDef>;
export type KSImportKeyword = InferNode<typeof ImportKeywordDef>;
export type KSInKeyword = InferNode<typeof InKeywordDef>;
export type KSInstanceOfKeyword = InferNode<typeof InstanceOfKeywordDef>;
export type KSNewKeyword = InferNode<typeof NewKeywordDef>;
export type KSNullKeyword = InferNode<typeof NullKeywordDef>;
export type KSReturnKeyword = InferNode<typeof ReturnKeywordDef>;
export type KSSuperKeyword = InferNode<typeof SuperKeywordDef>;
export type KSSwitchKeyword = InferNode<typeof SwitchKeywordDef>;
export type KSThisKeyword = InferNode<typeof ThisKeywordDef>;
export type KSThrowKeyword = InferNode<typeof ThrowKeywordDef>;
export type KSTrueKeyword = InferNode<typeof TrueKeywordDef>;
export type KSTryKeyword = InferNode<typeof TryKeywordDef>;
export type KSTypeOfKeyword = InferNode<typeof TypeOfKeywordDef>;
export type KSVarKeyword = InferNode<typeof VarKeywordDef>;
export type KSVoidKeyword = InferNode<typeof VoidKeywordDef>;
export type KSWhileKeyword = InferNode<typeof WhileKeywordDef>;
export type KSWithKeyword = InferNode<typeof WithKeywordDef>;
export type KSImplementsKeyword = InferNode<typeof ImplementsKeywordDef>;
export type KSInterfaceKeyword = InferNode<typeof InterfaceKeywordDef>;
export type KSLetKeyword = InferNode<typeof LetKeywordDef>;
export type KSPackageKeyword = InferNode<typeof PackageKeywordDef>;
export type KSPrivateKeyword = InferNode<typeof PrivateKeywordDef>;
export type KSProtectedKeyword = InferNode<typeof ProtectedKeywordDef>;
export type KSPublicKeyword = InferNode<typeof PublicKeywordDef>;
export type KSStaticKeyword = InferNode<typeof StaticKeywordDef>;
export type KSYieldKeyword = InferNode<typeof YieldKeywordDef>;
export type KSAbstractKeyword = InferNode<typeof AbstractKeywordDef>;
export type KSAccessorKeyword = InferNode<typeof AccessorKeywordDef>;
export type KSAsKeyword = InferNode<typeof AsKeywordDef>;
export type KSAssertsKeyword = InferNode<typeof AssertsKeywordDef>;
export type KSAssertKeyword = InferNode<typeof AssertKeywordDef>;
export type KSAnyKeyword = InferNode<typeof AnyKeywordDef>;
export type KSAsyncKeyword = InferNode<typeof AsyncKeywordDef>;
export type KSAwaitKeyword = InferNode<typeof AwaitKeywordDef>;
export type KSBooleanKeyword = InferNode<typeof BooleanKeywordDef>;
export type KSConstructorKeyword = InferNode<typeof ConstructorKeywordDef>;
export type KSDeclareKeyword = InferNode<typeof DeclareKeywordDef>;
export type KSGetKeyword = InferNode<typeof GetKeywordDef>;
export type KSInferKeyword = InferNode<typeof InferKeywordDef>;
export type KSIntrinsicKeyword = InferNode<typeof IntrinsicKeywordDef>;
export type KSIsKeyword = InferNode<typeof IsKeywordDef>;
export type KSKeyOfKeyword = InferNode<typeof KeyOfKeywordDef>;
export type KSModuleKeyword = InferNode<typeof ModuleKeywordDef>;
export type KSNamespaceKeyword = InferNode<typeof NamespaceKeywordDef>;
export type KSNeverKeyword = InferNode<typeof NeverKeywordDef>;
export type KSOutKeyword = InferNode<typeof OutKeywordDef>;
export type KSReadonlyKeyword = InferNode<typeof ReadonlyKeywordDef>;
export type KSRequireKeyword = InferNode<typeof RequireKeywordDef>;
export type KSNumberKeyword = InferNode<typeof NumberKeywordDef>;
export type KSObjectKeyword = InferNode<typeof ObjectKeywordDef>;
export type KSSatisfiesKeyword = InferNode<typeof SatisfiesKeywordDef>;
export type KSSetKeyword = InferNode<typeof SetKeywordDef>;
export type KSStringKeyword = InferNode<typeof StringKeywordDef>;
export type KSSymbolKeyword = InferNode<typeof SymbolKeywordDef>;
export type KSTypeKeyword = InferNode<typeof TypeKeywordDef>;
export type KSUndefinedKeyword = InferNode<typeof UndefinedKeywordDef>;
export type KSUniqueKeyword = InferNode<typeof UniqueKeywordDef>;
export type KSUnknownKeyword = InferNode<typeof UnknownKeywordDef>;
export type KSUsingKeyword = InferNode<typeof UsingKeywordDef>;
export type KSFromKeyword = InferNode<typeof FromKeywordDef>;
export type KSGlobalKeyword = InferNode<typeof GlobalKeywordDef>;
export type KSBigIntKeyword = InferNode<typeof BigIntKeywordDef>;
export type KSOverrideKeyword = InferNode<typeof OverrideKeywordDef>;
export type KSOfKeyword = InferNode<typeof OfKeywordDef>;
export type KSDeferKeyword = InferNode<typeof DeferKeywordDef>;
export type KSJSDocAllType = InferNode<typeof JSDocAllTypeDef>;
export type KSJSDocUnknownType = InferNode<typeof JSDocUnknownTypeDef>;
export type KSJSDocNamepathType = InferNode<typeof JSDocNamepathTypeDef>;
export type KSJSDoc = InferNode<typeof JSDocDef>;
export type KSJSDocText = InferNode<typeof JSDocTextDef>;
export type KSJSDocSignature = InferNode<typeof JSDocSignatureDef>;
export type KSJSDocLink = InferNode<typeof JSDocLinkDef>;
export type KSJSDocLinkCode = InferNode<typeof JSDocLinkCodeDef>;
export type KSJSDocLinkPlain = InferNode<typeof JSDocLinkPlainDef>;
export type KSJSDocTag = InferNode<typeof JSDocTagDef>;
export type KSJSDocAugmentsTag = InferNode<typeof JSDocAugmentsTagDef>;
export type KSJSDocImplementsTag = InferNode<typeof JSDocImplementsTagDef>;
export type KSJSDocAuthorTag = InferNode<typeof JSDocAuthorTagDef>;
export type KSJSDocDeprecatedTag = InferNode<typeof JSDocDeprecatedTagDef>;
export type KSJSDocClassTag = InferNode<typeof JSDocClassTagDef>;
export type KSJSDocPublicTag = InferNode<typeof JSDocPublicTagDef>;
export type KSJSDocPrivateTag = InferNode<typeof JSDocPrivateTagDef>;
export type KSJSDocProtectedTag = InferNode<typeof JSDocProtectedTagDef>;
export type KSJSDocReadonlyTag = InferNode<typeof JSDocReadonlyTagDef>;
export type KSJSDocOverrideTag = InferNode<typeof JSDocOverrideTagDef>;
export type KSJSDocCallbackTag = InferNode<typeof JSDocCallbackTagDef>;
export type KSJSDocOverloadTag = InferNode<typeof JSDocOverloadTagDef>;
export type KSJSDocEnumTag = InferNode<typeof JSDocEnumTagDef>;
export type KSJSDocParameterTag = InferNode<typeof JSDocParameterTagDef>;
export type KSJSDocReturnTag = InferNode<typeof JSDocReturnTagDef>;
export type KSJSDocThisTag = InferNode<typeof JSDocThisTagDef>;
export type KSJSDocTypeTag = InferNode<typeof JSDocTypeTagDef>;
export type KSJSDocTemplateTag = InferNode<typeof JSDocTemplateTagDef>;
export type KSJSDocTypedefTag = InferNode<typeof JSDocTypedefTagDef>;
export type KSJSDocSeeTag = InferNode<typeof JSDocSeeTagDef>;
export type KSJSDocPropertyTag = InferNode<typeof JSDocPropertyTagDef>;
export type KSJSDocThrowsTag = InferNode<typeof JSDocThrowsTagDef>;
export type KSJSDocSatisfiesTag = InferNode<typeof JSDocSatisfiesTagDef>;
export type KSJSDocImportTag = InferNode<typeof JSDocImportTagDef>;
export type KSSyntaxList = InferNode<typeof SyntaxListDef>;
export type KSNotEmittedStatement = InferNode<typeof NotEmittedStatementDef>;
export type KSNotEmittedTypeElement = InferNode<typeof NotEmittedTypeElementDef>;
export type KSSyntheticExpression = InferNode<typeof SyntheticExpressionDef>;
export type KSSyntheticReferenceExpression = InferNode<typeof SyntheticReferenceExpressionDef>;
export type KSBundle = InferNode<typeof BundleDef>;
export type KSImportTypeAssertionContainer = InferNode<typeof ImportTypeAssertionContainerDef>;
export type KSBigIntLiteral = InferNode<typeof BigIntLiteralDef>;
export type KSRegularExpressionLiteral = InferNode<typeof RegularExpressionLiteralDef>;
export type KSTemplateHead = InferNode<typeof TemplateHeadDef>;
export type KSTemplateMiddle = InferNode<typeof TemplateMiddleDef>;
export type KSTemplateTail = InferNode<typeof TemplateTailDef>;
export type KSJsxText = InferNode<typeof JsxTextDef>;
export type KSPrivateIdentifier = InferNode<typeof PrivateIdentifierDef>;
export type KSQualifiedName = InferNode<typeof QualifiedNameDef>;
export type KSDecorator = InferNode<typeof DecoratorDef>;
export type KSMethodSignature = InferNode<typeof MethodSignatureDef>;
export type KSClassStaticBlockDeclaration = InferNode<typeof ClassStaticBlockDeclarationDef>;
export type KSCallSignature = InferNode<typeof CallSignatureDef>;
export type KSConstructSignature = InferNode<typeof ConstructSignatureDef>;
export type KSIndexSignature = InferNode<typeof IndexSignatureDef>;
export type KSTypePredicate = InferNode<typeof TypePredicateDef>;
export type KSConstructorType = InferNode<typeof ConstructorTypeDef>;
export type KSOptionalType = InferNode<typeof OptionalTypeDef>;
export type KSRestType = InferNode<typeof RestTypeDef>;
export type KSInferType = InferNode<typeof InferTypeDef>;
export type KSParenthesizedType = InferNode<typeof ParenthesizedTypeDef>;
export type KSThisType = InferNode<typeof ThisTypeDef>;
export type KSTypeOperator = InferNode<typeof TypeOperatorDef>;
export type KSNamedTupleMember = InferNode<typeof NamedTupleMemberDef>;
export type KSTemplateLiteralType = InferNode<typeof TemplateLiteralTypeDef>;
export type KSTemplateLiteralTypeSpan = InferNode<typeof TemplateLiteralTypeSpanDef>;
export type KSImportType = InferNode<typeof ImportTypeDef>;
export type KSObjectBindingPattern = InferNode<typeof ObjectBindingPatternDef>;
export type KSArrayBindingPattern = InferNode<typeof ArrayBindingPatternDef>;
export type KSBindingElement = InferNode<typeof BindingElementDef>;
export type KSTaggedTemplateExpression = InferNode<typeof TaggedTemplateExpressionDef>;
export type KSTypeAssertionExpression = InferNode<typeof TypeAssertionExpressionDef>;
export type KSDeleteExpression = InferNode<typeof DeleteExpressionDef>;
export type KSTypeOfExpression = InferNode<typeof TypeOfExpressionDef>;
export type KSVoidExpression = InferNode<typeof VoidExpressionDef>;
export type KSYieldExpression = InferNode<typeof YieldExpressionDef>;
export type KSClassExpression = InferNode<typeof ClassExpressionDef>;
export type KSOmittedExpression = InferNode<typeof OmittedExpressionDef>;
export type KSExpressionWithTypeArguments = InferNode<typeof ExpressionWithTypeArgumentsDef>;
export type KSNonNullExpression = InferNode<typeof NonNullExpressionDef>;
export type KSMetaProperty = InferNode<typeof MetaPropertyDef>;
export type KSSatisfiesExpression = InferNode<typeof SatisfiesExpressionDef>;
export type KSTemplateSpan = InferNode<typeof TemplateSpanDef>;
export type KSSemicolonClassElement = InferNode<typeof SemicolonClassElementDef>;
export type KSEmptyStatement = InferNode<typeof EmptyStatementDef>;
export type KSContinueStatement = InferNode<typeof ContinueStatementDef>;
export type KSBreakStatement = InferNode<typeof BreakStatementDef>;
export type KSWithStatement = InferNode<typeof WithStatementDef>;
export type KSLabeledStatement = InferNode<typeof LabeledStatementDef>;
export type KSDebuggerStatement = InferNode<typeof DebuggerStatementDef>;
export type KSModuleDeclaration = InferNode<typeof ModuleDeclarationDef>;
export type KSModuleBlock = InferNode<typeof ModuleBlockDef>;
export type KSNamespaceExportDeclaration = InferNode<typeof NamespaceExportDeclarationDef>;
export type KSImportEqualsDeclaration = InferNode<typeof ImportEqualsDeclarationDef>;
export type KSNamedExports = InferNode<typeof NamedExportsDef>;
export type KSNamespaceExport = InferNode<typeof NamespaceExportDef>;
export type KSExportSpecifier = InferNode<typeof ExportSpecifierDef>;
export type KSExternalModuleReference = InferNode<typeof ExternalModuleReferenceDef>;
export type KSJsxElement = InferNode<typeof JsxElementDef>;
export type KSJsxSelfClosingElement = InferNode<typeof JsxSelfClosingElementDef>;
export type KSJsxOpeningElement = InferNode<typeof JsxOpeningElementDef>;
export type KSJsxClosingElement = InferNode<typeof JsxClosingElementDef>;
export type KSJsxFragment = InferNode<typeof JsxFragmentDef>;
export type KSJsxOpeningFragment = InferNode<typeof JsxOpeningFragmentDef>;
export type KSJsxClosingFragment = InferNode<typeof JsxClosingFragmentDef>;
export type KSJsxAttribute = InferNode<typeof JsxAttributeDef>;
export type KSJsxAttributes = InferNode<typeof JsxAttributesDef>;
export type KSJsxSpreadAttribute = InferNode<typeof JsxSpreadAttributeDef>;
export type KSJsxExpression = InferNode<typeof JsxExpressionDef>;
export type KSJsxNamespacedName = InferNode<typeof JsxNamespacedNameDef>;
export type KSImportAttributes = InferNode<typeof ImportAttributesDef>;
export type KSImportAttribute = InferNode<typeof ImportAttributeDef>;
export type KSSpreadAssignment = InferNode<typeof SpreadAssignmentDef>;
export type KSJSDocTypeExpression = InferNode<typeof JSDocTypeExpressionDef>;
export type KSJSDocNameReference = InferNode<typeof JSDocNameReferenceDef>;
export type KSJSDocMemberName = InferNode<typeof JSDocMemberNameDef>;
export type KSJSDocNullableType = InferNode<typeof JSDocNullableTypeDef>;
export type KSJSDocNonNullableType = InferNode<typeof JSDocNonNullableTypeDef>;
export type KSJSDocOptionalType = InferNode<typeof JSDocOptionalTypeDef>;
export type KSJSDocFunctionType = InferNode<typeof JSDocFunctionTypeDef>;
export type KSJSDocVariadicType = InferNode<typeof JSDocVariadicTypeDef>;
export type KSJSDocTypeLiteral = InferNode<typeof JSDocTypeLiteralDef>;
export type KSPartiallyEmittedExpression = InferNode<typeof PartiallyEmittedExpressionDef>;
export type KSCommaListExpression = InferNode<typeof CommaListExpressionDef>;
export type KSMissingDeclaration = InferNode<typeof MissingDeclarationDef>;

// ═══════════════════════════════════════════════════════════════════════
// KSNode union type
// ═══════════════════════════════════════════════════════════════════════

export type KSNode =
  | KSProgram
  | KSCompilationUnit
  | KSTypeAliasDeclaration
  | KSInterfaceDeclaration
  | KSFunctionDeclaration
  | KSClassDeclaration
  | KSEnumDeclaration
  | KSVariableStatement
  | KSVariableDeclarationList
  | KSVariableDeclaration
  | KSImportDeclaration
  | KSImportClause
  | KSNamedImports
  | KSImportSpecifier
  | KSNamespaceImport
  | KSExportDeclaration
  | KSExportAssignment
  | KSBlock
  | KSExpressionStatement
  | KSReturnStatement
  | KSIfStatement
  | KSForStatement
  | KSForOfStatement
  | KSForInStatement
  | KSWhileStatement
  | KSDoStatement
  | KSSwitchStatement
  | KSThrowStatement
  | KSTryStatement
  | KSCallExpression
  | KSPropertyAccessExpression
  | KSElementAccessExpression
  | KSBinaryExpression
  | KSPrefixUnaryExpression
  | KSPostfixUnaryExpression
  | KSArrowFunction
  | KSFunctionExpression
  | KSObjectLiteralExpression
  | KSArrayLiteralExpression
  | KSTemplateExpression
  | KSConditionalExpression
  | KSNewExpression
  | KSAwaitExpression
  | KSSpreadElement
  | KSAsExpression
  | KSParenthesizedExpression
  | KSTypeReferenceNode
  | KSTypeLiteralNode
  | KSUnionType
  | KSIntersectionType
  | KSFunctionType
  | KSArrayType
  | KSTupleType
  | KSLiteralType
  | KSConditionalType
  | KSMappedType
  | KSIndexedAccessType
  | KSTypeQuery
  | KSIdentifier
  | KSStringLiteral
  | KSNumericLiteral
  | KSNoSubstitutionTemplateLiteral
  | KSPropertySignature
  | KSPropertyDeclaration
  | KSMethodDeclaration
  | KSConstructorDeclaration
  | KSGetAccessorDeclaration
  | KSSetAccessorDeclaration
  | KSParameterNode
  | KSTypeParameterNode
  | KSPropertyAssignment
  | KSShorthandPropertyAssignment
  | KSComputedPropertyName
  | KSHeritageClause
  | KSCatchClause
  | KSCaseBlock
  | KSCaseClause
  | KSDefaultClause
  | KSEnumMember
  | KSUnknown
  | KSEndOfFileToken
  | KSSingleLineCommentTrivia
  | KSMultiLineCommentTrivia
  | KSNewLineTrivia
  | KSWhitespaceTrivia
  | KSShebangTrivia
  | KSConflictMarkerTrivia
  | KSNonTextFileMarkerTrivia
  | KSJsxTextAllWhiteSpaces
  | KSOpenBraceToken
  | KSCloseBraceToken
  | KSOpenParenToken
  | KSCloseParenToken
  | KSOpenBracketToken
  | KSCloseBracketToken
  | KSDotToken
  | KSDotDotDotToken
  | KSSemicolonToken
  | KSCommaToken
  | KSQuestionDotToken
  | KSLessThanToken
  | KSLessThanSlashToken
  | KSGreaterThanToken
  | KSLessThanEqualsToken
  | KSGreaterThanEqualsToken
  | KSEqualsEqualsToken
  | KSExclamationEqualsToken
  | KSEqualsEqualsEqualsToken
  | KSExclamationEqualsEqualsToken
  | KSEqualsGreaterThanToken
  | KSPlusToken
  | KSMinusToken
  | KSAsteriskToken
  | KSAsteriskAsteriskToken
  | KSSlashToken
  | KSPercentToken
  | KSPlusPlusToken
  | KSMinusMinusToken
  | KSLessThanLessThanToken
  | KSGreaterThanGreaterThanToken
  | KSGreaterThanGreaterThanGreaterThanToken
  | KSAmpersandToken
  | KSBarToken
  | KSCaretToken
  | KSExclamationToken
  | KSTildeToken
  | KSAmpersandAmpersandToken
  | KSBarBarToken
  | KSQuestionToken
  | KSColonToken
  | KSAtToken
  | KSQuestionQuestionToken
  | KSBacktickToken
  | KSHashToken
  | KSEqualsToken
  | KSPlusEqualsToken
  | KSMinusEqualsToken
  | KSAsteriskEqualsToken
  | KSAsteriskAsteriskEqualsToken
  | KSSlashEqualsToken
  | KSPercentEqualsToken
  | KSLessThanLessThanEqualsToken
  | KSGreaterThanGreaterThanEqualsToken
  | KSGreaterThanGreaterThanGreaterThanEqualsToken
  | KSAmpersandEqualsToken
  | KSBarEqualsToken
  | KSBarBarEqualsToken
  | KSAmpersandAmpersandEqualsToken
  | KSQuestionQuestionEqualsToken
  | KSCaretEqualsToken
  | KSJSDocCommentTextToken
  | KSBreakKeyword
  | KSCaseKeyword
  | KSCatchKeyword
  | KSClassKeyword
  | KSConstKeyword
  | KSContinueKeyword
  | KSDebuggerKeyword
  | KSDefaultKeyword
  | KSDeleteKeyword
  | KSDoKeyword
  | KSElseKeyword
  | KSEnumKeyword
  | KSExportKeyword
  | KSExtendsKeyword
  | KSFalseKeyword
  | KSFinallyKeyword
  | KSForKeyword
  | KSFunctionKeyword
  | KSIfKeyword
  | KSImportKeyword
  | KSInKeyword
  | KSInstanceOfKeyword
  | KSNewKeyword
  | KSNullKeyword
  | KSReturnKeyword
  | KSSuperKeyword
  | KSSwitchKeyword
  | KSThisKeyword
  | KSThrowKeyword
  | KSTrueKeyword
  | KSTryKeyword
  | KSTypeOfKeyword
  | KSVarKeyword
  | KSVoidKeyword
  | KSWhileKeyword
  | KSWithKeyword
  | KSImplementsKeyword
  | KSInterfaceKeyword
  | KSLetKeyword
  | KSPackageKeyword
  | KSPrivateKeyword
  | KSProtectedKeyword
  | KSPublicKeyword
  | KSStaticKeyword
  | KSYieldKeyword
  | KSAbstractKeyword
  | KSAccessorKeyword
  | KSAsKeyword
  | KSAssertsKeyword
  | KSAssertKeyword
  | KSAnyKeyword
  | KSAsyncKeyword
  | KSAwaitKeyword
  | KSBooleanKeyword
  | KSConstructorKeyword
  | KSDeclareKeyword
  | KSGetKeyword
  | KSInferKeyword
  | KSIntrinsicKeyword
  | KSIsKeyword
  | KSKeyOfKeyword
  | KSModuleKeyword
  | KSNamespaceKeyword
  | KSNeverKeyword
  | KSOutKeyword
  | KSReadonlyKeyword
  | KSRequireKeyword
  | KSNumberKeyword
  | KSObjectKeyword
  | KSSatisfiesKeyword
  | KSSetKeyword
  | KSStringKeyword
  | KSSymbolKeyword
  | KSTypeKeyword
  | KSUndefinedKeyword
  | KSUniqueKeyword
  | KSUnknownKeyword
  | KSUsingKeyword
  | KSFromKeyword
  | KSGlobalKeyword
  | KSBigIntKeyword
  | KSOverrideKeyword
  | KSOfKeyword
  | KSDeferKeyword
  | KSJSDocAllType
  | KSJSDocUnknownType
  | KSJSDocNamepathType
  | KSJSDoc
  | KSJSDocText
  | KSJSDocSignature
  | KSJSDocLink
  | KSJSDocLinkCode
  | KSJSDocLinkPlain
  | KSJSDocTag
  | KSJSDocAugmentsTag
  | KSJSDocImplementsTag
  | KSJSDocAuthorTag
  | KSJSDocDeprecatedTag
  | KSJSDocClassTag
  | KSJSDocPublicTag
  | KSJSDocPrivateTag
  | KSJSDocProtectedTag
  | KSJSDocReadonlyTag
  | KSJSDocOverrideTag
  | KSJSDocCallbackTag
  | KSJSDocOverloadTag
  | KSJSDocEnumTag
  | KSJSDocParameterTag
  | KSJSDocReturnTag
  | KSJSDocThisTag
  | KSJSDocTypeTag
  | KSJSDocTemplateTag
  | KSJSDocTypedefTag
  | KSJSDocSeeTag
  | KSJSDocPropertyTag
  | KSJSDocThrowsTag
  | KSJSDocSatisfiesTag
  | KSJSDocImportTag
  | KSSyntaxList
  | KSNotEmittedStatement
  | KSNotEmittedTypeElement
  | KSSyntheticExpression
  | KSSyntheticReferenceExpression
  | KSBundle
  | KSImportTypeAssertionContainer
  | KSBigIntLiteral
  | KSRegularExpressionLiteral
  | KSTemplateHead
  | KSTemplateMiddle
  | KSTemplateTail
  | KSJsxText
  | KSPrivateIdentifier
  | KSQualifiedName
  | KSDecorator
  | KSMethodSignature
  | KSClassStaticBlockDeclaration
  | KSCallSignature
  | KSConstructSignature
  | KSIndexSignature
  | KSTypePredicate
  | KSConstructorType
  | KSOptionalType
  | KSRestType
  | KSInferType
  | KSParenthesizedType
  | KSThisType
  | KSTypeOperator
  | KSNamedTupleMember
  | KSTemplateLiteralType
  | KSTemplateLiteralTypeSpan
  | KSImportType
  | KSObjectBindingPattern
  | KSArrayBindingPattern
  | KSBindingElement
  | KSTaggedTemplateExpression
  | KSTypeAssertionExpression
  | KSDeleteExpression
  | KSTypeOfExpression
  | KSVoidExpression
  | KSYieldExpression
  | KSClassExpression
  | KSOmittedExpression
  | KSExpressionWithTypeArguments
  | KSNonNullExpression
  | KSMetaProperty
  | KSSatisfiesExpression
  | KSTemplateSpan
  | KSSemicolonClassElement
  | KSEmptyStatement
  | KSContinueStatement
  | KSBreakStatement
  | KSWithStatement
  | KSLabeledStatement
  | KSDebuggerStatement
  | KSModuleDeclaration
  | KSModuleBlock
  | KSNamespaceExportDeclaration
  | KSImportEqualsDeclaration
  | KSNamedExports
  | KSNamespaceExport
  | KSExportSpecifier
  | KSExternalModuleReference
  | KSJsxElement
  | KSJsxSelfClosingElement
  | KSJsxOpeningElement
  | KSJsxClosingElement
  | KSJsxFragment
  | KSJsxOpeningFragment
  | KSJsxClosingFragment
  | KSJsxAttribute
  | KSJsxAttributes
  | KSJsxSpreadAttribute
  | KSJsxExpression
  | KSJsxNamespacedName
  | KSImportAttributes
  | KSImportAttribute
  | KSSpreadAssignment
  | KSJSDocTypeExpression
  | KSJSDocNameReference
  | KSJSDocMemberName
  | KSJSDocNullableType
  | KSJSDocNonNullableType
  | KSJSDocOptionalType
  | KSJSDocFunctionType
  | KSJSDocVariadicType
  | KSJSDocTypeLiteral
  | KSPartiallyEmittedExpression
  | KSCommaListExpression
  | KSMissingDeclaration;

// ═══════════════════════════════════════════════════════════════════════
// All node definitions (for schema creation)
// ═══════════════════════════════════════════════════════════════════════

export const allNodeDefs: NodeDef[] = [
  ProgramDef,
  CompilationUnitDef,
  TypeAliasDeclarationDef,
  InterfaceDeclarationDef,
  FunctionDeclarationDef,
  ClassDeclarationDef,
  EnumDeclarationDef,
  VariableStatementDef,
  VariableDeclarationListDef,
  VariableDeclarationDef,
  ImportDeclarationDef,
  ImportClauseDef,
  NamedImportsDef,
  ImportSpecifierDef,
  NamespaceImportDef,
  ExportDeclarationDef,
  ExportAssignmentDef,
  BlockDef,
  ExpressionStatementDef,
  ReturnStatementDef,
  IfStatementDef,
  ForStatementDef,
  ForOfStatementDef,
  ForInStatementDef,
  WhileStatementDef,
  DoStatementDef,
  SwitchStatementDef,
  ThrowStatementDef,
  TryStatementDef,
  CallExpressionDef,
  PropertyAccessExpressionDef,
  ElementAccessExpressionDef,
  BinaryExpressionDef,
  PrefixUnaryExpressionDef,
  PostfixUnaryExpressionDef,
  ArrowFunctionDef,
  FunctionExpressionDef,
  ObjectLiteralExpressionDef,
  ArrayLiteralExpressionDef,
  TemplateExpressionDef,
  ConditionalExpressionDef,
  NewExpressionDef,
  AwaitExpressionDef,
  SpreadElementDef,
  AsExpressionDef,
  ParenthesizedExpressionDef,
  TypeReferenceNodeDef,
  TypeLiteralNodeDef,
  UnionTypeDef,
  IntersectionTypeDef,
  FunctionTypeDef,
  ArrayTypeDef,
  TupleTypeDef,
  LiteralTypeDef,
  ConditionalTypeDef,
  MappedTypeDef,
  IndexedAccessTypeDef,
  TypeQueryDef,
  IdentifierDef,
  StringLiteralDef,
  NumericLiteralDef,
  NoSubstitutionTemplateLiteralDef,
  PropertySignatureDef,
  PropertyDeclarationDef,
  MethodDeclarationDef,
  ConstructorDeclarationDef,
  GetAccessorDeclarationDef,
  SetAccessorDeclarationDef,
  ParameterNodeDef,
  TypeParameterNodeDef,
  PropertyAssignmentDef,
  ShorthandPropertyAssignmentDef,
  ComputedPropertyNameDef,
  HeritageClauseDef,
  CatchClauseDef,
  CaseBlockDef,
  CaseClauseDef,
  DefaultClauseDef,
  EnumMemberDef,
  UnknownDef,
  EndOfFileTokenDef,
  SingleLineCommentTriviaDef,
  MultiLineCommentTriviaDef,
  NewLineTriviaDef,
  WhitespaceTriviaDef,
  ShebangTriviaDef,
  ConflictMarkerTriviaDef,
  NonTextFileMarkerTriviaDef,
  JsxTextAllWhiteSpacesDef,
  OpenBraceTokenDef,
  CloseBraceTokenDef,
  OpenParenTokenDef,
  CloseParenTokenDef,
  OpenBracketTokenDef,
  CloseBracketTokenDef,
  DotTokenDef,
  DotDotDotTokenDef,
  SemicolonTokenDef,
  CommaTokenDef,
  QuestionDotTokenDef,
  LessThanTokenDef,
  LessThanSlashTokenDef,
  GreaterThanTokenDef,
  LessThanEqualsTokenDef,
  GreaterThanEqualsTokenDef,
  EqualsEqualsTokenDef,
  ExclamationEqualsTokenDef,
  EqualsEqualsEqualsTokenDef,
  ExclamationEqualsEqualsTokenDef,
  EqualsGreaterThanTokenDef,
  PlusTokenDef,
  MinusTokenDef,
  AsteriskTokenDef,
  AsteriskAsteriskTokenDef,
  SlashTokenDef,
  PercentTokenDef,
  PlusPlusTokenDef,
  MinusMinusTokenDef,
  LessThanLessThanTokenDef,
  GreaterThanGreaterThanTokenDef,
  GreaterThanGreaterThanGreaterThanTokenDef,
  AmpersandTokenDef,
  BarTokenDef,
  CaretTokenDef,
  ExclamationTokenDef,
  TildeTokenDef,
  AmpersandAmpersandTokenDef,
  BarBarTokenDef,
  QuestionTokenDef,
  ColonTokenDef,
  AtTokenDef,
  QuestionQuestionTokenDef,
  BacktickTokenDef,
  HashTokenDef,
  EqualsTokenDef,
  PlusEqualsTokenDef,
  MinusEqualsTokenDef,
  AsteriskEqualsTokenDef,
  AsteriskAsteriskEqualsTokenDef,
  SlashEqualsTokenDef,
  PercentEqualsTokenDef,
  LessThanLessThanEqualsTokenDef,
  GreaterThanGreaterThanEqualsTokenDef,
  GreaterThanGreaterThanGreaterThanEqualsTokenDef,
  AmpersandEqualsTokenDef,
  BarEqualsTokenDef,
  BarBarEqualsTokenDef,
  AmpersandAmpersandEqualsTokenDef,
  QuestionQuestionEqualsTokenDef,
  CaretEqualsTokenDef,
  JSDocCommentTextTokenDef,
  BreakKeywordDef,
  CaseKeywordDef,
  CatchKeywordDef,
  ClassKeywordDef,
  ConstKeywordDef,
  ContinueKeywordDef,
  DebuggerKeywordDef,
  DefaultKeywordDef,
  DeleteKeywordDef,
  DoKeywordDef,
  ElseKeywordDef,
  EnumKeywordDef,
  ExportKeywordDef,
  ExtendsKeywordDef,
  FalseKeywordDef,
  FinallyKeywordDef,
  ForKeywordDef,
  FunctionKeywordDef,
  IfKeywordDef,
  ImportKeywordDef,
  InKeywordDef,
  InstanceOfKeywordDef,
  NewKeywordDef,
  NullKeywordDef,
  ReturnKeywordDef,
  SuperKeywordDef,
  SwitchKeywordDef,
  ThisKeywordDef,
  ThrowKeywordDef,
  TrueKeywordDef,
  TryKeywordDef,
  TypeOfKeywordDef,
  VarKeywordDef,
  VoidKeywordDef,
  WhileKeywordDef,
  WithKeywordDef,
  ImplementsKeywordDef,
  InterfaceKeywordDef,
  LetKeywordDef,
  PackageKeywordDef,
  PrivateKeywordDef,
  ProtectedKeywordDef,
  PublicKeywordDef,
  StaticKeywordDef,
  YieldKeywordDef,
  AbstractKeywordDef,
  AccessorKeywordDef,
  AsKeywordDef,
  AssertsKeywordDef,
  AssertKeywordDef,
  AnyKeywordDef,
  AsyncKeywordDef,
  AwaitKeywordDef,
  BooleanKeywordDef,
  ConstructorKeywordDef,
  DeclareKeywordDef,
  GetKeywordDef,
  InferKeywordDef,
  IntrinsicKeywordDef,
  IsKeywordDef,
  KeyOfKeywordDef,
  ModuleKeywordDef,
  NamespaceKeywordDef,
  NeverKeywordDef,
  OutKeywordDef,
  ReadonlyKeywordDef,
  RequireKeywordDef,
  NumberKeywordDef,
  ObjectKeywordDef,
  SatisfiesKeywordDef,
  SetKeywordDef,
  StringKeywordDef,
  SymbolKeywordDef,
  TypeKeywordDef,
  UndefinedKeywordDef,
  UniqueKeywordDef,
  UnknownKeywordDef,
  UsingKeywordDef,
  FromKeywordDef,
  GlobalKeywordDef,
  BigIntKeywordDef,
  OverrideKeywordDef,
  OfKeywordDef,
  DeferKeywordDef,
  JSDocAllTypeDef,
  JSDocUnknownTypeDef,
  JSDocNamepathTypeDef,
  JSDocDef,
  JSDocTextDef,
  JSDocSignatureDef,
  JSDocLinkDef,
  JSDocLinkCodeDef,
  JSDocLinkPlainDef,
  JSDocTagDef,
  JSDocAugmentsTagDef,
  JSDocImplementsTagDef,
  JSDocAuthorTagDef,
  JSDocDeprecatedTagDef,
  JSDocClassTagDef,
  JSDocPublicTagDef,
  JSDocPrivateTagDef,
  JSDocProtectedTagDef,
  JSDocReadonlyTagDef,
  JSDocOverrideTagDef,
  JSDocCallbackTagDef,
  JSDocOverloadTagDef,
  JSDocEnumTagDef,
  JSDocParameterTagDef,
  JSDocReturnTagDef,
  JSDocThisTagDef,
  JSDocTypeTagDef,
  JSDocTemplateTagDef,
  JSDocTypedefTagDef,
  JSDocSeeTagDef,
  JSDocPropertyTagDef,
  JSDocThrowsTagDef,
  JSDocSatisfiesTagDef,
  JSDocImportTagDef,
  SyntaxListDef,
  NotEmittedStatementDef,
  NotEmittedTypeElementDef,
  SyntheticExpressionDef,
  SyntheticReferenceExpressionDef,
  BundleDef,
  ImportTypeAssertionContainerDef,
  BigIntLiteralDef,
  RegularExpressionLiteralDef,
  TemplateHeadDef,
  TemplateMiddleDef,
  TemplateTailDef,
  JsxTextDef,
  PrivateIdentifierDef,
  QualifiedNameDef,
  DecoratorDef,
  MethodSignatureDef,
  ClassStaticBlockDeclarationDef,
  CallSignatureDef,
  ConstructSignatureDef,
  IndexSignatureDef,
  TypePredicateDef,
  ConstructorTypeDef,
  OptionalTypeDef,
  RestTypeDef,
  InferTypeDef,
  ParenthesizedTypeDef,
  ThisTypeDef,
  TypeOperatorDef,
  NamedTupleMemberDef,
  TemplateLiteralTypeDef,
  TemplateLiteralTypeSpanDef,
  ImportTypeDef,
  ObjectBindingPatternDef,
  ArrayBindingPatternDef,
  BindingElementDef,
  TaggedTemplateExpressionDef,
  TypeAssertionExpressionDef,
  DeleteExpressionDef,
  TypeOfExpressionDef,
  VoidExpressionDef,
  YieldExpressionDef,
  ClassExpressionDef,
  OmittedExpressionDef,
  ExpressionWithTypeArgumentsDef,
  NonNullExpressionDef,
  MetaPropertyDef,
  SatisfiesExpressionDef,
  TemplateSpanDef,
  SemicolonClassElementDef,
  EmptyStatementDef,
  ContinueStatementDef,
  BreakStatementDef,
  WithStatementDef,
  LabeledStatementDef,
  DebuggerStatementDef,
  ModuleDeclarationDef,
  ModuleBlockDef,
  NamespaceExportDeclarationDef,
  ImportEqualsDeclarationDef,
  NamedExportsDef,
  NamespaceExportDef,
  ExportSpecifierDef,
  ExternalModuleReferenceDef,
  JsxElementDef,
  JsxSelfClosingElementDef,
  JsxOpeningElementDef,
  JsxClosingElementDef,
  JsxFragmentDef,
  JsxOpeningFragmentDef,
  JsxClosingFragmentDef,
  JsxAttributeDef,
  JsxAttributesDef,
  JsxSpreadAttributeDef,
  JsxExpressionDef,
  JsxNamespacedNameDef,
  ImportAttributesDef,
  ImportAttributeDef,
  SpreadAssignmentDef,
  JSDocTypeExpressionDef,
  JSDocNameReferenceDef,
  JSDocMemberNameDef,
  JSDocNullableTypeDef,
  JSDocNonNullableTypeDef,
  JSDocOptionalTypeDef,
  JSDocFunctionTypeDef,
  JSDocVariadicTypeDef,
  JSDocTypeLiteralDef,
  PartiallyEmittedExpressionDef,
  CommaListExpressionDef,
  MissingDeclarationDef,
];

// ═══════════════════════════════════════════════════════════════════════
// Schema (runtime introspection, derived getChildren, completeness checking)
// ═══════════════════════════════════════════════════════════════════════

export const ksNodeSchema = createNodeSchema<KSNode>(allNodeDefs);

/**
 * Schema-derived getChildren. Replaces the hand-written version in ast.ts.
 *
 * For Program → compilationUnits (from named children).
 * For nodes with named children → collects them in declaration order.
 * For leaf nodes → falls back to flat children array.
 */
export const getChildren: (node: KSNode) => KSNode[] = ksNodeSchema.getChildren;
