/**
 * Shared TS-frontend convert.ts skeleton.
 *
 * Emits the infrastructure template (preamble + postamble) for convert.ts files
 * that target the TypeScript compiler API. Both the real TS AST grammar and the
 * mock grammar reuse this skeleton, differing only in optional configuration.
 *
 * NOTE: This file does NOT import 'typescript' — it generates string templates
 * that contain TS-specific code.
 */

// ── Configuration ─────────────────────────────────────────────────────

export interface ConvertSkeletonConfig {
  /** Optional helper imports: { module, names } added as an import line. */
  helperImport?: {
    module: string;
    names: string[];
  };
  /** Optional init call inserted at the top of buildKSTree. */
  buildKSTreeInit?: string;
  /** If true, declares a module-level _ctx variable for stateful helper functions. */
  usesConvertContext?: boolean;
}

// ── Preamble ──────────────────────────────────────────────────────────

export function emitConvertPreamble(config: ConvertSkeletonConfig = {}): string {
  const importLines = [`import ts from 'typescript';`, `import type * as KS from './node-types.js';`];
  if (config.helperImport) {
    const { module, names } = config.helperImport;
    importLines.push(`import { ${names.join(', ')} } from '${module}';`);
  }

  return `/**
 * AUTO-GENERATED by compileGrammar — do not edit.
 *
 * TS → KS AST conversion layer.
 * Walks the TypeScript AST and produces a KS mirror tree.
 */

${importLines.join('\n')}

export interface KSTree {
  root: KS.KSProgram;
}

export type AnalysisDepth = 'parse' | 'bind' | 'check';

// ── Identity map ──

const tsToKs = new WeakMap<ts.Node, KS.KSNode>();

// ── Comment handling ──

function toCommentRange(cr: ts.CommentRange): KS.KSCommentRange {
  return {
    pos: cr.pos,
    end: cr.end,
    kind: cr.kind === ts.SyntaxKind.SingleLineCommentTrivia ? 'SingleLine' : 'MultiLine',
    hasTrailingNewLine: cr.hasTrailingNewLine,
  };
}

function attachComments(ksNode: KS.KSNode, tsNode: ts.Node, sf: ts.SourceFile): void {
  const sourceText = sf.getFullText();
  const leading = ts.getLeadingCommentRanges(sourceText, tsNode.getFullStart());
  const trailing = ts.getTrailingCommentRanges(sourceText, tsNode.getEnd());
  if (leading && leading.length > 0) {
    (ksNode as any).leadingComments = leading.map(toCommentRange);
  }
  if (trailing && trailing.length > 0) {
    (ksNode as any).trailingComments = trailing.map(toCommentRange);
  }
}

// ── Child lookup ──

function findChild<T extends KS.KSNode = KS.KSNode>(
  children: KS.KSNode[],
  tsTarget: ts.Node | undefined,
): T | undefined {
  if (!tsTarget) return undefined;
  return tsToKs.get(tsTarget) as T | undefined;
}

function findChildrenOf<T extends KS.KSNode = KS.KSNode>(
  children: KS.KSNode[],
  tsTargets: ts.NodeArray<ts.Node> | readonly ts.Node[] | undefined,
): T[] {
  if (!tsTargets) return [];
  return (tsTargets as readonly ts.Node[]).map((t) => tsToKs.get(t)!).filter(Boolean) as T[];
}

// ── Converter registry ──

type SpecificConverter = (
  node: ts.Node,
  sf: ts.SourceFile,
  children: KS.KSNode[],
  pos: number,
  end: number,
  text: string,
) => KS.KSNode;

const specificConverters: Partial<Record<number, SpecificConverter>> = {};

function register(kind: number, converter: SpecificConverter): void {
  specificConverters[kind] = converter;
}
${config.usesConvertContext ? `
// ── Convert context ──

let _ctx: { checker: ts.TypeChecker | undefined; depth: AnalysisDepth };
` : ''}
`;
}

// ── Postamble ─────────────────────────────────────────────────────────

export function emitConvertPostamble(config: ConvertSkeletonConfig = {}): string {
  const initLines = config.buildKSTreeInit
    ? `\n  ${config.buildKSTreeInit}`
    : '';

  return `// ── Central dispatch ──

function convertNode(node: ts.Node, sf: ts.SourceFile): KS.KSNode {
  const children: KS.KSNode[] = [];
  ts.forEachChild(node, (child) => {
    children.push(convertNode(child, sf));
  });

  const pos = node.getStart(sf);
  const end = node.getEnd();
  let text: string;
  try {
    text = node.getText(sf);
  } catch {
    text = '';
  }

  const converter = specificConverters[node.kind];
  if (converter) {
    const ksNode = converter(node, sf, children, pos, end, text);
    attachComments(ksNode, node, sf);
    tsToKs.set(node, ksNode);
    return ksNode;
  }

  throw new Error(\`Unhandled SyntaxKind: \${ts.SyntaxKind[node.kind] ?? node.kind}\`);
}

// ── SourceFile → CompilationUnit ──

function convertSourceFile(sf: ts.SourceFile): KS.KSCompilationUnit {
  const children: KS.KSNode[] = [];
  ts.forEachChild(sf, (child) => {
    children.push(convertNode(child, sf));
  });

  const cu: KS.KSCompilationUnit = {
    kind: 'CompilationUnit',
    fileName: sf.fileName,
    isDeclarationFile: sf.isDeclarationFile,
    sourceText: sf.getFullText(),
    lineStarts: sf.getLineStarts(),
    languageVariant: sf.languageVariant === ts.LanguageVariant.JSX ? 'JSX' : 'Standard',
    pos: sf.getStart(),
    end: sf.getEnd(),
    text: '',
    children,
  };
  tsToKs.set(sf, cu);
  return cu;
}

// ── Public API ──

export function buildKSTree(tsProgram: ts.Program, depth: AnalysisDepth = 'check'): KSTree {${initLines}
  const compilationUnits: KS.KSCompilationUnit[] = [];

  for (const sf of tsProgram.getSourceFiles()) {
    if (sf.isDeclarationFile) continue;
    compilationUnits.push(convertSourceFile(sf));
  }

  const root: KS.KSProgram = {
    kind: 'Program',
    compilationUnits,
    pos: 0,
    end: 0,
    text: '',
    children: compilationUnits,
  };

  return { root };
}
`;
}
