/**
 * Codegen script — imports the schema and generates output files.
 *
 * Usage: npx tsx ast-schema/codegen.ts
 *
 * Generates:
 *   ast-schema/generated/node-types.ts  — interfaces, unions, type guards
 *   ast-schema/generated/schema.ts      — getChildren, allKinds, getChildFields
 *   ast-schema/generated/convert.ts     — TS → KS AST conversion
 *   ast-schema/generated/index.ts       — barrel re-export
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

// Import schema (side-effect: populates registries)
import './schema.js';
import {
  getNodeRegistry,
  getSumTypeRegistry,
  type NodeEntry,
  type SumTypeEntry,
  type FieldDesc,
} from './builder.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.join(__dirname, 'generated');

// ── Helpers ──────────────────────────────────────────────────────────

function ksTypeName(kind: string): string {
  return `KS${kind}`;
}

/** Resolve a field's type ref to a KS TypeScript type string */
function resolveFieldType(field: FieldDesc, sumTypes: Map<string, SumTypeEntry>): string {
  if (field.tag === 'prop') return field.propType;

  const ref = field.typeRef;
  if (!ref) return 'KSNode'; // untyped = any node

  // If it's a sum type name, use the sum type alias
  if (sumTypes.has(ref)) return `KS${ref}`;

  // Otherwise it's a specific node kind
  return ksTypeName(ref);
}


// ── Load registries ──────────────────────────────────────────────────

const nodes = getNodeRegistry();
const sumTypes = getSumTypeRegistry();

console.log(`Schema loaded: ${nodes.size} nodes, ${sumTypes.size} sum types`);
for (const [name, st] of sumTypes) {
  console.log(`  ${name}: ${st.members.length} members`);
}

// Count complex vs leaf
let complexCount = 0, leafCount = 0;
let fieldCount = 0;
for (const [, entry] of nodes) {
  const fc = Object.keys(entry.fields).length;
  if (fc > 0) { complexCount++; fieldCount += fc; }
  else leafCount++;
}
console.log(`Complex: ${complexCount}, Leaf: ${leafCount}, Fields: ${fieldCount}`);

// ── Generate node-types.ts ───────────────────────────────────────────

function generateNodeTypes(): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * AUTO-GENERATED by ast-schema/codegen.ts — do not edit.`);
  lines.push(` *`);
  lines.push(` * TypeScript interfaces, union types, and type guards for all AST nodes.`);
  lines.push(` */`);
  lines.push(``);

  // Comment range type
  lines.push(`export interface KSCommentRange {`);
  lines.push(`  pos: number;`);
  lines.push(`  end: number;`);
  lines.push(`  kind: 'SingleLine' | 'MultiLine';`);
  lines.push(`  hasTrailingNewLine?: boolean;`);
  lines.push(`}`);
  lines.push(``);

  // Base type
  lines.push(`/** Fields shared by every KS node. */`);
  lines.push(`export interface KSNodeBase {`);
  lines.push(`  kind: string;`);
  lines.push(`  pos: number;`);
  lines.push(`  end: number;`);
  lines.push(`  text: string;`);
  lines.push(`  children: KSNode[];`);
  lines.push(`  leadingComments?: KSCommentRange[];`);
  lines.push(`  trailingComments?: KSCommentRange[];`);
  lines.push(`}`);
  lines.push(``);

  // All node interfaces
  for (const [kind, entry] of nodes) {
    const typeName = ksTypeName(kind);
    const fieldEntries = Object.entries(entry.fields);

    if (fieldEntries.length === 0) {
      // Leaf node
      lines.push(`export interface ${typeName} extends KSNodeBase {`);
      lines.push(`  kind: '${kind}';`);
      lines.push(`}`);
    } else {
      lines.push(`export interface ${typeName} extends KSNodeBase {`);
      lines.push(`  kind: '${kind}';`);
      for (const [fname, field] of fieldEntries) {
        const tsType = resolveFieldType(field, sumTypes);
        switch (field.tag) {
          case 'child':
            lines.push(`  ${fname}: ${tsType};`);
            break;
          case 'optChild':
            lines.push(`  ${fname}: ${tsType} | undefined;`);
            break;
          case 'list':
            lines.push(`  ${fname}: ${tsType}[];`);
            break;
          case 'prop':
            lines.push(`  ${fname}: ${tsType};`);
            break;
        }
      }
      lines.push(`}`);
    }
    lines.push(``);
  }

  // KSNode union
  const allKinds = [...nodes.keys()];
  lines.push(`// ── KSNode union ──`);
  lines.push(``);
  lines.push(`export type KSNode =`);
  for (let i = 0; i < allKinds.length; i++) {
    const sep = i === allKinds.length - 1 ? ';' : '';
    lines.push(`  | ${ksTypeName(allKinds[i])}${sep}`);
  }
  lines.push(``);

  // Sum type unions
  lines.push(`// ── Sum type unions ──`);
  lines.push(``);
  for (const [name, st] of sumTypes) {
    if (st.members.length === 0) continue;
    lines.push(`export type KS${name} =`);
    for (let i = 0; i < st.members.length; i++) {
      const sep = i === st.members.length - 1 ? ';' : '';
      lines.push(`  | ${ksTypeName(st.members[i])}${sep}`);
    }
    lines.push(``);
  }

  // Type guard functions
  lines.push(`// ── Type guards ──`);
  lines.push(``);
  for (const [name, st] of sumTypes) {
    if (st.members.length === 0) continue;
    const kindSet = st.members.map(m => `'${m}'`).join(', ');
    lines.push(`const ${name}Kinds = new Set([${kindSet}]);`);
    lines.push(`export function is${name}(node: KSNode): node is KS${name} {`);
    lines.push(`  return ${name}Kinds.has(node.kind);`);
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join('\n');
}

// ── Generate schema.ts (replaces node-defs.ts + node-schema.ts) ─────

function generateSchema(): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * AUTO-GENERATED by ast-schema/codegen.ts — do not edit.`);
  lines.push(` *`);
  lines.push(` * Static schema: getChildren, allKinds, getChildFields.`);
  lines.push(` * No runtime library dependencies — pure generated code.`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`import type { KSNode } from './node-types.js';`);
  lines.push(``);

  // ── Child field metadata table (internal) ──
  // Every kind has an entry: complete schema, no fallback needed.
  // - Kinds with child/optChild/list fields: their field names
  // - CompilationUnit: ['children'] (uses generic children array as child container)
  // - All other kinds (true leaves): [] (no children)
  lines.push(`// Child field names per node kind (declaration order).`);
  lines.push(`// Every kind has an entry — the schema is exhaustive.`);
  lines.push(`const C: Record<string, readonly string[]> = {`);
  for (const [kind, entry] of nodes) {
    const childFieldNames: string[] = [];
    for (const [fname, field] of Object.entries(entry.fields)) {
      if (field.tag !== 'prop') {
        childFieldNames.push(fname);
      }
    }
    if (childFieldNames.length > 0) {
      lines.push(`  '${kind}': [${childFieldNames.map(f => `'${f}'`).join(', ')}],`);
    } else if (kind === 'CompilationUnit') {
      // CompilationUnit stores child statements in KSNodeBase.children
      lines.push(`  '${kind}': ['children'],`);
    } else {
      lines.push(`  '${kind}': [],`);
    }
  }
  lines.push(`};`);
  lines.push(``);

  // ── getChildren ──
  lines.push(`/**`);
  lines.push(` * Collect child nodes in declaration order.`);
  lines.push(` * Reads named child/optChild/list fields from the exhaustive schema.`);
  lines.push(` * Leaf nodes return [].`);
  lines.push(` */`);
  lines.push(`export function getChildren(node: KSNode): KSNode[] {`);
  lines.push(`  const fields = C[node.kind];`);
  lines.push(`  if (!fields || fields.length === 0) return [];`);
  lines.push(`  const result: KSNode[] = [];`);
  lines.push(`  for (const f of fields) {`);
  lines.push(`    const v = (node as any)[f];`);
  lines.push(`    if (v == null) continue;`);
  lines.push(`    if (Array.isArray(v)) {`);
  lines.push(`      for (const item of v) if (item != null) result.push(item);`);
  lines.push(`    } else {`);
  lines.push(`      result.push(v);`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`  return result;`);
  lines.push(`}`);
  lines.push(``);

  // ── allKinds ──
  lines.push(`/** All ${nodes.size} node kind strings. */`);
  lines.push(`export const allKinds: ReadonlySet<string> = new Set([`);
  const allKindsList = [...nodes.keys()];
  for (let i = 0; i < allKindsList.length; i++) {
    lines.push(`  '${allKindsList[i]}',`);
  }
  lines.push(`]);`);
  lines.push(``);

  // ── getChildFields ──
  lines.push(`/** Child field names for a given kind. */`);
  lines.push(`export function getChildFields(kind: string): readonly string[] {`);
  lines.push(`  return C[kind] ?? [];`);
  lines.push(`}`);
  lines.push(``);

  // ── fieldDefs: full field definitions per kind ──
  lines.push(`/** Full field definitions per kind: name, tag, and optional type reference. */`);
  lines.push(`export interface FieldDef { name: string; tag: 'child' | 'optChild' | 'list' | 'prop'; typeRef?: string; }`);
  lines.push(`export const fieldDefs: Readonly<Record<string, readonly FieldDef[]>> = {`);
  for (const [kind, entry] of nodes) {
    const fieldEntries = Object.entries(entry.fields);
    if (fieldEntries.length === 0) continue;
    const items = fieldEntries.map(([fname, field]) => {
      const typeRef = field.tag === 'prop'
        ? field.propType
        : field.typeRef;
      const escaped = typeRef ? typeRef.replace(/'/g, "\\'") : undefined;
      const typeRefStr = escaped ? `, typeRef: '${escaped}'` : '';
      return `{ name: '${fname}', tag: '${field.tag}'${typeRefStr} }`;
    }).join(', ');
    lines.push(`  '${kind}': [${items}],`);
  }
  lines.push(`};`);
  lines.push(``);

  // ── sumTypeMembership: kind → sum type names ──
  lines.push(`/** Sum type memberships per kind. */`);
  lines.push(`export const sumTypeMembership: Readonly<Record<string, readonly string[]>> = {`);
  const kindToSumTypes = new Map<string, string[]>();
  for (const [name, st] of sumTypes) {
    for (const member of st.members) {
      if (!kindToSumTypes.has(member)) kindToSumTypes.set(member, []);
      kindToSumTypes.get(member)!.push(name);
    }
  }
  for (const [kind, stNames] of kindToSumTypes) {
    lines.push(`  '${kind}': [${stNames.map(n => `'${n}'`).join(', ')}],`);
  }
  lines.push(`};`);
  lines.push(``);

  return lines.join('\n');
}

// ── Generate convert.ts ──────────────────────────────────────────────

// KSC-only nodes (no ts.SyntaxKind equivalent)
const convertSkipNodes = new Set(['Program', 'CompilationUnit']);

// SyntaxKinds that exist at runtime but not in TS type declarations
// Map from node kind → numeric SyntaxKind value
const syntaxKindOverrides: Record<string, number> = {
  JSDocCommentTextToken: 82,
};

// JSDocNode sum type members (for auto-detecting comment fields)
const jsDocMembers = new Set(sumTypes.get('JSDocNode')?.members ?? []);

// Field-level overrides: [nodeKind][fieldName] → expression string
// Only for cases where TS stores data in a fundamentally different format.
// In expressions: n = node (as any), children = converted KS children
const convertFieldOverrides: Record<string, Record<string, string>> = {
  // Operator/token maps (TS stores as numeric SyntaxKind, we decode to string)
  PrefixUnaryExpression: { operator: 'prefixUnaryOperatorMap[n.operator]' },
  PostfixUnaryExpression: { operator: 'postfixUnaryOperatorMap[n.operator]' },
  TypeOperator: { operator: 'typeOperatorMap[n.operator]' },
  HeritageClause: { token: 'heritageTokenMap[n.token]' },
  MetaProperty: { keywordToken: 'metaPropertyKeywordMap[n.keywordToken]' },

  // Computed from NodeFlags (no direct TS property)
  VariableDeclarationList: { declarationKind: 'getDeclarationKind(n.flags)' },

  // Import resolution (uses TS checker, set by buildKSTree)
  Identifier: { resolvesToImport: 'isImportReference(node)' },
};

function getConvertFieldExpr(kind: string, fname: string, field: FieldDesc): string {
  // Explicit override
  const override = convertFieldOverrides[kind]?.[fname];
  if (override) return override;

  // Auto-detect: literal value/linkText → n.text
  // TS uses .text for the semantic value, but we rename to avoid collision
  // with the base KS .text property (source text).
  if ((fname === 'value' || fname === 'linkText') && field.tag === 'prop' && field.propType === 'string') {
    return 'n.text ?? ""';
  }

  // Auto-detect: JSDoc comment prop (TS .comment can be string | NodeArray)
  if (fname === 'comment' && field.tag === 'prop' && field.propType === 'string' && jsDocMembers.has(kind)) {
    return 'extractJSDocComment(n)';
  }

  // Default extraction by field tag
  switch (field.tag) {
    case 'child':    return `findChild(children, n.${fname})!`;
    case 'optChild': return `findChild(children, n.${fname})`;
    case 'list':     return `findChildrenOf(children, n.${fname})`;
    case 'prop': {
      if (field.propType === 'boolean') return `!!n.${fname}`;
      if (field.propType === 'string') return `n.${fname} ?? ""`;
      if (field.propType === 'readonly number[]') return `n.${fname} ?? []`;
      return `n.${fname}`;
    }
  }
}

function generateConvert(): string {
  const L: string[] = [];

  // ── Preamble ──
  L.push(`/**
 * AUTO-GENERATED by ast-schema/codegen.ts — do not edit.
 *
 * TS → KS AST conversion layer.
 * Walks the TypeScript AST and produces a KS mirror tree.
 */

import ts from 'typescript';
import type * as KS from './node-types.js';

export interface KSTree {
  root: KS.KSProgram;
}

// ── Identity map ──

const tsToKs = new WeakMap<ts.Node, KS.KSNode>();

// ── Checker (set by buildKSTree for import resolution) ──

let _checker: ts.TypeChecker | undefined;

function isImportReference(node: ts.Node): boolean {
  if (!_checker || !ts.isIdentifier(node)) return false;
  const sym = _checker.getSymbolAtLocation(node);
  if (!sym) return false;
  if (!(sym.flags & ts.SymbolFlags.Alias)) return false;
  // Verify it's a value-position reference (not type-only, not a definition site)
  const parent = node.parent;
  if (!parent) return false;
  // Skip declaration sites (import specifiers, import clause names, etc.)
  if (ts.isImportSpecifier(parent) || ts.isImportClause(parent) || ts.isNamespaceImport(parent)) return false;
  // Skip type-only positions
  if (ts.isTypeReferenceNode(parent) && parent.typeName === node) return false;
  if (ts.isTypeQueryNode(parent)) return false;
  // Skip definition sites
  if (ts.isVariableDeclaration(parent) && parent.name === node) return false;
  if (ts.isParameter(parent) && parent.name === node) return false;
  if (ts.isFunctionDeclaration(parent) && parent.name === node) return false;
  if (ts.isFunctionExpression(parent) && parent.name === node) return false;
  if (ts.isPropertyAccessExpression(parent) && parent.name === node) return false;
  if (ts.isPropertyAssignment(parent) && parent.name === node) return false;
  if (ts.isBindingElement(parent) && parent.name === node) return false;
  if (ts.isPropertySignature(parent) && parent.name === node) return false;
  if (ts.isTypeAliasDeclaration(parent) && parent.name === node) return false;
  return true;
}

// ── Comment handling ──

function toCommentRange(cr: ts.CommentRange): KS.KSCommentRange {
  return {
    pos: cr.pos,
    end: cr.end,
    kind: cr.kind === ts.SyntaxKind.SingleLineCommentTrivia ? 'SingleLine' : 'MultiLine',
    hasTrailingNewLine: cr.hasTrailingNewLine,
  };
}

function attachComments(ksNode: KS.KSNode, tsNode: ts.Node, sf: ts.SourceFile): void {
  const sourceText = sf.getFullText();
  const leading = ts.getLeadingCommentRanges(sourceText, tsNode.getFullStart());
  const trailing = ts.getTrailingCommentRanges(sourceText, tsNode.getEnd());
  if (leading && leading.length > 0) {
    (ksNode as any).leadingComments = leading.map(toCommentRange);
  }
  if (trailing && trailing.length > 0) {
    (ksNode as any).trailingComments = trailing.map(toCommentRange);
  }
}

// ── Child lookup ──

function findChild<T extends KS.KSNode = KS.KSNode>(
  children: KS.KSNode[],
  tsTarget: ts.Node | undefined,
): T | undefined {
  if (!tsTarget) return undefined;
  return tsToKs.get(tsTarget) as T | undefined;
}

function findChildrenOf<T extends KS.KSNode = KS.KSNode>(
  children: KS.KSNode[],
  tsTargets: ts.NodeArray<ts.Node> | readonly ts.Node[] | undefined,
): T[] {
  if (!tsTargets) return [];
  return (tsTargets as readonly ts.Node[]).map((t) => tsToKs.get(t)!).filter(Boolean) as T[];
}

// ── JSDoc comment extraction ──

function extractJSDocComment(n: any): string {
  if (!n.comment) return '';
  if (typeof n.comment === 'string') return n.comment;
  return '';
}

// ── Operator maps ──

const prefixUnaryOperatorMap: Record<number, string> = {
  [ts.SyntaxKind.PlusToken]: '+',
  [ts.SyntaxKind.MinusToken]: '-',
  [ts.SyntaxKind.TildeToken]: '~',
  [ts.SyntaxKind.ExclamationToken]: '!',
  [ts.SyntaxKind.PlusPlusToken]: '++',
  [ts.SyntaxKind.MinusMinusToken]: '--',
};

const postfixUnaryOperatorMap: Record<number, string> = {
  [ts.SyntaxKind.PlusPlusToken]: '++',
  [ts.SyntaxKind.MinusMinusToken]: '--',
};

const typeOperatorMap: Record<number, string> = {
  [ts.SyntaxKind.KeyOfKeyword]: 'keyof',
  [ts.SyntaxKind.UniqueKeyword]: 'unique',
  [ts.SyntaxKind.ReadonlyKeyword]: 'readonly',
};

const heritageTokenMap: Record<number, string> = {
  [ts.SyntaxKind.ExtendsKeyword]: 'extends',
  [ts.SyntaxKind.ImplementsKeyword]: 'implements',
};

const metaPropertyKeywordMap: Record<number, string> = {
  [ts.SyntaxKind.NewKeyword]: 'new',
  [ts.SyntaxKind.ImportKeyword]: 'import',
};

// ── Declaration kind helper ──

function getDeclarationKind(flags: number): 'var' | 'let' | 'const' | 'using' | 'await using' {
  if (flags & ts.NodeFlags.Const) return 'const';
  if (flags & ts.NodeFlags.Let) return 'let';
  if (flags & (ts.NodeFlags as any).AwaitUsing) return 'await using';
  if (flags & (ts.NodeFlags as any).Using) return 'using';
  return 'var';
}

// ── Converter registry ──

type SpecificConverter = (
  node: ts.Node,
  sf: ts.SourceFile,
  children: KS.KSNode[],
  pos: number,
  end: number,
  text: string,
) => KS.KSNode;

const specificConverters: Partial<Record<number, SpecificConverter>> = {};

function register(kind: number, converter: SpecificConverter): void {
  specificConverters[kind] = converter;
}

// ── Generated converters ──
`);

  // ── Generate converter for each node ──
  for (const [kind, entry] of nodes) {
    if (convertSkipNodes.has(kind)) continue;

    const fieldEntries = Object.entries(entry.fields);

    const syntaxKindExpr = syntaxKindOverrides[kind] !== undefined
      ? `${syntaxKindOverrides[kind]} as ts.SyntaxKind`
      : `ts.SyntaxKind.${kind}`;

    if (fieldEntries.length === 0) {
      // Leaf converter
      L.push(`register(${syntaxKindExpr}, (node, sf, children, pos, end, text) => ({`);
      L.push(`  kind: '${kind}', pos, end, text, children,`);
      L.push(`} as KS.KSNode));`);
    } else {
      // Complex converter
      L.push(`register(${syntaxKindExpr}, (node, sf, children, pos, end, text) => {`);
      L.push(`  const n = node as any;`);
      L.push(`  return {`);
      L.push(`    kind: '${kind}',`);
      for (const [fname, field] of fieldEntries) {
        const expr = getConvertFieldExpr(kind, fname, field);
        L.push(`    ${fname}: ${expr},`);
      }
      L.push(`    pos, end, text, children,`);
      L.push(`  } as KS.KSNode;`);
      L.push(`});`);
    }
    L.push(``);
  }

  // ── Postamble ──
  L.push(`// ── Central dispatch ──

function convertNode(node: ts.Node, sf: ts.SourceFile): KS.KSNode {
  const children: KS.KSNode[] = [];
  ts.forEachChild(node, (child) => {
    children.push(convertNode(child, sf));
  });

  const pos = node.getStart(sf);
  const end = node.getEnd();
  let text: string;
  try {
    text = node.getText(sf);
  } catch {
    text = '';
  }

  const converter = specificConverters[node.kind];
  if (converter) {
    const ksNode = converter(node, sf, children, pos, end, text);
    attachComments(ksNode, node, sf);
    tsToKs.set(node, ksNode);
    return ksNode;
  }

  throw new Error(\`Unhandled SyntaxKind: \${ts.SyntaxKind[node.kind] ?? node.kind}\`);
}

// ── SourceFile → CompilationUnit ──

function convertSourceFile(sf: ts.SourceFile): KS.KSCompilationUnit {
  const children: KS.KSNode[] = [];
  ts.forEachChild(sf, (child) => {
    children.push(convertNode(child, sf));
  });

  const cu: KS.KSCompilationUnit = {
    kind: 'CompilationUnit',
    fileName: sf.fileName,
    isDeclarationFile: sf.isDeclarationFile,
    sourceText: sf.getFullText(),
    lineStarts: sf.getLineStarts(),
    languageVariant: sf.languageVariant === ts.LanguageVariant.JSX ? 'JSX' : 'Standard',
    pos: sf.getStart(),
    end: sf.getEnd(),
    text: '',
    children,
  };
  tsToKs.set(sf, cu);
  return cu;
}

// ── Public API ──

export function buildKSTree(tsProgram: ts.Program): KSTree {
  _checker = tsProgram.getTypeChecker();
  const compilationUnits: KS.KSCompilationUnit[] = [];

  for (const sf of tsProgram.getSourceFiles()) {
    if (sf.isDeclarationFile) continue;
    compilationUnits.push(convertSourceFile(sf));
  }

  const root: KS.KSProgram = {
    kind: 'Program',
    compilationUnits,
    pos: 0,
    end: 0,
    text: '',
    children: compilationUnits,
  };

  return { root };
}
`);

  return L.join('\n');
}

// ── Generate builders.ts ─────────────────────────────────────────────

function generateBuilders(): string {
  const L: string[] = [];
  L.push(`/**`);
  L.push(` * AUTO-GENERATED by ast-schema/codegen.ts — do not edit.`);
  L.push(` *`);
  L.push(` * Factory functions for constructing KS AST nodes without parsing.`);
  L.push(` * Every createXxx() produces a valid node with children computed from fields.`);
  L.push(` */`);
  L.push(``);

  // Collect all types needed for imports
  const referencedTypes = new Set<string>();
  referencedTypes.add('KSNode');
  for (const [kind, entry] of nodes) {
    referencedTypes.add(ksTypeName(kind));
    for (const [, field] of Object.entries(entry.fields)) {
      if (field.tag === 'prop') continue;
      const ref = field.typeRef;
      if (!ref) continue;
      if (sumTypes.has(ref)) referencedTypes.add(`KS${ref}`);
      else referencedTypes.add(ksTypeName(ref));
    }
  }
  const sortedRefs = [...referencedTypes].sort();
  L.push(`import type {`);
  for (const ref of sortedRefs) {
    L.push(`  ${ref},`);
  }
  L.push(`} from './node-types.js';`);
  L.push(``);

  for (const [kind, entry] of nodes) {
    const fieldEntries = Object.entries(entry.fields);

    if (fieldEntries.length === 0) {
      // Leaf builder — no fields
      L.push(`export function create${kind}(): ${ksTypeName(kind)} {`);
      L.push(`  return { kind: '${kind}', pos: 0, end: 0, text: '', children: [] };`);
      L.push(`}`);
    } else {
      // Build the fields interface inline
      const paramFields: string[] = [];
      const requiredFields: string[] = [];
      const optionalFields: string[] = [];

      for (const [fname, field] of fieldEntries) {
        const tsType = resolveFieldType(field, sumTypes);
        switch (field.tag) {
          case 'child':
            paramFields.push(`  ${fname}: ${tsType};`);
            requiredFields.push(fname);
            break;
          case 'optChild':
            paramFields.push(`  ${fname}?: ${tsType};`);
            optionalFields.push(fname);
            break;
          case 'list':
            paramFields.push(`  ${fname}?: ${tsType}[];`);
            optionalFields.push(fname);
            break;
          case 'prop':
            // Props with boolean default to false, strings to '', arrays to []
            if (tsType === 'boolean') {
              paramFields.push(`  ${fname}?: ${tsType};`);
              optionalFields.push(fname);
            } else if (tsType === 'string') {
              paramFields.push(`  ${fname}?: ${tsType};`);
              optionalFields.push(fname);
            } else {
              paramFields.push(`  ${fname}?: ${tsType};`);
              optionalFields.push(fname);
            }
            break;
        }
      }

      // If all fields are optional, make the whole param optional via default
      const allOptional = requiredFields.length === 0;
      const paramSuffix = allOptional ? ' = {}' : '';

      L.push(`export function create${kind}(fields: {`);
      for (const pf of paramFields) L.push(pf);
      L.push(`}${paramSuffix}): ${ksTypeName(kind)} {`);

      // Build children array from child/optChild/list fields
      const childExprs: string[] = [];
      for (const [fname, field] of fieldEntries) {
        switch (field.tag) {
          case 'child':
            childExprs.push(`fields.${fname}`);
            break;
          case 'optChild':
            childExprs.push(`...(fields.${fname} ? [fields.${fname}] : [])`);
            break;
          case 'list':
            childExprs.push(`...(fields.${fname} ?? [])`);
            break;
        }
      }

      L.push(`  const children: KSNode[] = [${childExprs.join(', ')}];`);
      L.push(`  return {`);
      L.push(`    kind: '${kind}',`);
      for (const [fname, field] of fieldEntries) {
        switch (field.tag) {
          case 'child':
            L.push(`    ${fname}: fields.${fname},`);
            break;
          case 'optChild':
            L.push(`    ${fname}: fields.${fname},`);
            break;
          case 'list':
            L.push(`    ${fname}: fields.${fname} ?? [],`);
            break;
          case 'prop': {
            const tsType = resolveFieldType(field, sumTypes);
            if (tsType === 'boolean') {
              L.push(`    ${fname}: fields.${fname} ?? false,`);
            } else if (tsType === 'string') {
              L.push(`    ${fname}: fields.${fname} ?? '',`);
            } else if (tsType === 'readonly number[]') {
              L.push(`    ${fname}: fields.${fname} ?? [],`);
            } else {
              // Union literal types — use first option as default
              const match = tsType.match(/^'([^']+)'/);
              if (match) {
                L.push(`    ${fname}: fields.${fname} ?? '${match[1]}',`);
              } else {
                L.push(`    ${fname}: fields.${fname}!,`);
              }
            }
            break;
          }
        }
      }
      L.push(`    pos: 0, end: 0, text: '', children,`);
      L.push(`  };`);
      L.push(`}`);
    }
    L.push(``);
  }

  return L.join('\n');
}

// ── Generate serialize.ts ────────────────────────────────────────────

function generateSerializer(): string {
  const L: string[] = [];
  L.push(`/**`);
  L.push(` * AUTO-GENERATED by ast-schema/codegen.ts — do not edit.`);
  L.push(` *`);
  L.push(` * Schema-aware AST serialization.`);
  L.push(` * - nodeToJSON: KSNode → plain JSON object (typed fields preserved).`);
  L.push(` * - nodeFromJSON: plain JSON → KSNode (typed fields + children reconstructed).`);
  L.push(` * - treeToJSON / treeFromJSON: operate on KSTree (root + compilationUnits).`);
  L.push(` */`);
  L.push(``);
  L.push(`import type { KSNode, KSCommentRange } from './node-types.js';`);
  L.push(``);

  // Generate field metadata table
  L.push(`// Field metadata: [fieldName, tag] tuples per node kind.`);
  L.push(`// tag: 'c' = child, 'o' = optChild, 'l' = list, 'p' = prop`);
  L.push(`type FieldTag = 'c' | 'o' | 'l' | 'p';`);
  L.push(`const F: Record<string, [string, FieldTag][]> = {`);
  for (const [kind, entry] of nodes) {
    const fieldEntries = Object.entries(entry.fields);
    if (fieldEntries.length === 0) continue;
    const tuples = fieldEntries.map(([fname, field]) => {
      const tag = field.tag === 'child' ? 'c' : field.tag === 'optChild' ? 'o' : field.tag === 'list' ? 'l' : 'p';
      return `['${fname}','${tag}']`;
    }).join(',');
    L.push(`  '${kind}': [${tuples}],`);
  }
  L.push(`};`);
  L.push(``);

  // Identify nodes whose schema fields have no child/optChild/list (only props).
  // These nodes may still have children in the generic `children` array (e.g. CompilationUnit).
  const propsOnlyKinds = new Set<string>();
  for (const [kind, entry] of nodes) {
    const fieldEntries = Object.entries(entry.fields);
    if (fieldEntries.length === 0) continue; // leaf nodes handled separately
    const hasChildField = fieldEntries.some(([, f]) => f.tag === 'child' || f.tag === 'optChild' || f.tag === 'list');
    if (!hasChildField) propsOnlyKinds.add(kind);
  }
  if (propsOnlyKinds.size > 0) {
    L.push(`// Nodes with only prop fields — may have untyped children in children array.`);
    L.push(`const PROPS_ONLY = new Set([${[...propsOnlyKinds].map(k => `'${k}'`).join(',')}]);`);
    L.push(``);
  }

  // JSON node type
  L.push(`/** JSON-safe representation of a KS node. */`);
  L.push(`export interface JSONNode {`);
  L.push(`  kind: string;`);
  L.push(`  pos: number;`);
  L.push(`  end: number;`);
  L.push(`  text?: string;`);
  L.push(`  children?: JSONNode[];`);
  L.push(`  leadingComments?: KSCommentRange[];`);
  L.push(`  trailingComments?: KSCommentRange[];`);
  L.push(`  [key: string]: unknown;`);
  L.push(`}`);
  L.push(``);

  // nodeToJSON
  L.push(`/** Serialize a single KSNode to a JSON-safe plain object. */`);
  L.push(`export function nodeToJSON(node: KSNode): JSONNode {`);
  L.push(`  const result: JSONNode = { kind: node.kind, pos: node.pos, end: node.end };`);
  L.push(`  if (node.text) result.text = node.text;`);
  L.push(`  if (node.leadingComments) result.leadingComments = node.leadingComments;`);
  L.push(`  if (node.trailingComments) result.trailingComments = node.trailingComments;`);
  L.push(`  const fields = F[node.kind];`);
  L.push(`  if (fields) {`);
  L.push(`    const n = node as any;`);
  L.push(`    for (const [name, tag] of fields) {`);
  L.push(`      const val = n[name];`);
  L.push(`      switch (tag) {`);
  L.push(`        case 'c': result[name] = nodeToJSON(val); break;`);
  L.push(`        case 'o': if (val != null) result[name] = nodeToJSON(val); break;`);
  L.push(`        case 'l': if (val && val.length > 0) result[name] = val.map(nodeToJSON); break;`);
  L.push(`        case 'p': if (val !== undefined && val !== '' && val !== false) result[name] = val; break;`);
  L.push(`      }`);
  L.push(`    }`);
  L.push(`  }`);
  L.push(`  // For nodes with only prop fields (e.g. CompilationUnit), serialize children array`);
  L.push(`  if (PROPS_ONLY.has(node.kind) && node.children.length > 0) {`);
  L.push(`    result.children = node.children.map(nodeToJSON);`);
  L.push(`  }`);
  L.push(`  return result;`);
  L.push(`}`);
  L.push(``);

  // nodeFromJSON
  L.push(`/** Deserialize a JSON object back to a KSNode with typed fields + children. */`);
  L.push(`export function nodeFromJSON(data: JSONNode): KSNode {`);
  L.push(`  const children: KSNode[] = [];`);
  L.push(`  const node: any = {`);
  L.push(`    kind: data.kind,`);
  L.push(`    pos: data.pos ?? 0,`);
  L.push(`    end: data.end ?? 0,`);
  L.push(`    text: data.text ?? '',`);
  L.push(`  };`);
  L.push(`  if (data.leadingComments) node.leadingComments = data.leadingComments;`);
  L.push(`  if (data.trailingComments) node.trailingComments = data.trailingComments;`);
  L.push(`  const fields = F[data.kind];`);
  L.push(`  if (fields) {`);
  L.push(`    for (const [name, tag] of fields) {`);
  L.push(`      switch (tag) {`);
  L.push(`        case 'c': {`);
  L.push(`          const child = nodeFromJSON(data[name] as JSONNode);`);
  L.push(`          node[name] = child;`);
  L.push(`          children.push(child);`);
  L.push(`          break;`);
  L.push(`        }`);
  L.push(`        case 'o': {`);
  L.push(`          if (data[name] != null) {`);
  L.push(`            const child = nodeFromJSON(data[name] as JSONNode);`);
  L.push(`            node[name] = child;`);
  L.push(`            children.push(child);`);
  L.push(`          } else {`);
  L.push(`            node[name] = undefined;`);
  L.push(`          }`);
  L.push(`          break;`);
  L.push(`        }`);
  L.push(`        case 'l': {`);
  L.push(`          const arr = data[name] as JSONNode[] | undefined;`);
  L.push(`          if (arr && arr.length > 0) {`);
  L.push(`            const items = arr.map(nodeFromJSON);`);
  L.push(`            node[name] = items;`);
  L.push(`            children.push(...items);`);
  L.push(`          } else {`);
  L.push(`            node[name] = [];`);
  L.push(`          }`);
  L.push(`          break;`);
  L.push(`        }`);
  L.push(`        case 'p': {`);
  L.push(`          node[name] = data[name] ?? propDefault(data.kind, name);`);
  L.push(`          break;`);
  L.push(`        }`);
  L.push(`      }`);
  L.push(`    }`);
  L.push(`  }`);
  L.push(`  // For props-only nodes with serialized children, restore from children array`);
  L.push(`  if (children.length === 0 && data.children && data.children.length > 0) {`);
  L.push(`    children.push(...data.children.map(nodeFromJSON));`);
  L.push(`  }`);
  L.push(`  node.children = children;`);
  L.push(`  return node as KSNode;`);
  L.push(`}`);
  L.push(``);

  // Generate prop defaults table (only for non-trivial defaults)
  L.push(`// Prop defaults by kind+field for deserialization.`);
  L.push(`const PD: Record<string, Record<string, unknown>> = {`);
  for (const [kind, entry] of nodes) {
    const propDefaults: [string, string][] = [];
    for (const [fname, field] of Object.entries(entry.fields)) {
      if (field.tag !== 'prop') continue;
      if (field.propType === 'boolean') {
        propDefaults.push([fname, 'false']);
      } else if (field.propType === 'string') {
        propDefaults.push([fname, `''`]);
      } else if (field.propType === 'readonly number[]') {
        propDefaults.push([fname, '[]']);
      } else {
        // Union literals — default to first option
        const match = field.propType.match(/^'([^']+)'/);
        if (match) propDefaults.push([fname, `'${match[1]}'`]);
      }
    }
    if (propDefaults.length > 0) {
      const entries = propDefaults.map(([f, v]) => `${f}:${v}`).join(',');
      L.push(`  '${kind}': {${entries}},`);
    }
  }
  L.push(`};`);
  L.push(``);
  L.push(`function propDefault(kind: string, name: string): unknown {`);
  L.push(`  return PD[kind]?.[name] ?? '';`);
  L.push(`}`);
  L.push(``);

  // treeToJSON / treeFromJSON
  L.push(`/** JSON-safe KSTree representation. */`);
  L.push(`export interface JSONTree {`);
  L.push(`  root: JSONNode;`);
  L.push(`}`);
  L.push(``);
  L.push(`/** Serialize a KSTree (root with compilationUnits) to JSON. */`);
  L.push(`export function treeToJSON(tree: { root: KSNode }): JSONTree {`);
  L.push(`  return { root: nodeToJSON(tree.root) };`);
  L.push(`}`);
  L.push(``);
  L.push(`/** Deserialize a JSON tree back to a KSTree with typed fields. */`);
  L.push(`export function treeFromJSON(data: JSONTree): { root: KSNode } {`);
  L.push(`  const root = nodeFromJSON(data.root);`);
  L.push(`  // Reconstruct compilationUnits for Program nodes`);
  L.push(`  if (root.kind === 'Program') {`);
  L.push(`    (root as any).compilationUnits = root.children;`);
  L.push(`  }`);
  L.push(`  return { root };`);
  L.push(`}`);
  L.push(``);

  return L.join('\n');
}

// ── Generate index.ts ────────────────────────────────────────────────

function generateIndex(): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * AUTO-GENERATED by ast-schema/codegen.ts — do not edit.`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`// Types and interfaces`);
  lines.push(`export type {`);
  lines.push(`  KSCommentRange,`);
  lines.push(`  KSNodeBase,`);
  lines.push(`  KSNode,`);

  // Export all node type names
  for (const kind of nodes.keys()) {
    lines.push(`  ${ksTypeName(kind)},`);
  }

  // Export sum type names
  for (const [name, st] of sumTypes) {
    if (st.members.length > 0) {
      lines.push(`  KS${name},`);
    }
  }

  lines.push(`} from './node-types.js';`);
  lines.push(``);

  // Export type guards
  lines.push(`// Type guards`);
  lines.push(`export {`);
  for (const [name, st] of sumTypes) {
    if (st.members.length > 0) {
      lines.push(`  is${name},`);
    }
  }
  lines.push(`} from './node-types.js';`);
  lines.push(``);

  // Schema (getChildren, allKinds, getChildFields)
  lines.push(`// Schema`);
  lines.push(`export { getChildren, allKinds, getChildFields, fieldDefs, sumTypeMembership, type FieldDef } from './schema.js';`);
  lines.push(``);

  // Builders
  lines.push(`// Node builders`);
  lines.push(`export {`);
  for (const kind of nodes.keys()) {
    lines.push(`  create${kind},`);
  }
  lines.push(`} from './builders.js';`);
  lines.push(``);

  // Serialization
  lines.push(`// Schema-aware serialization`);
  lines.push(`export {`);
  lines.push(`  type JSONNode,`);
  lines.push(`  type JSONTree,`);
  lines.push(`  nodeToJSON,`);
  lines.push(`  nodeFromJSON,`);
  lines.push(`  treeToJSON,`);
  lines.push(`  treeFromJSON,`);
  lines.push(`} from './serialize.js';`);
  lines.push(``);

  return lines.join('\n');
}

// ── Write files ──────────────────────────────────────────────────────

fs.mkdirSync(OUT_DIR, { recursive: true });

const files = [
  { name: 'node-types.ts', content: generateNodeTypes() },
  { name: 'schema.ts', content: generateSchema() },
  { name: 'convert.ts', content: generateConvert() },
  { name: 'builders.ts', content: generateBuilders() },
  { name: 'serialize.ts', content: generateSerializer() },
  { name: 'index.ts', content: generateIndex() },
];

for (const file of files) {
  const outPath = path.join(OUT_DIR, file.name);
  fs.writeFileSync(outPath, file.content, 'utf-8');
  const lineCount = file.content.split('\n').length;
  console.log(`  Generated ${file.name} (${lineCount} lines)`);
}

console.log('\nDone!');
