/**
 * Migration script: Parse ast.ts and generate node-defs.ts with defineNode() calls.
 *
 * Reads the existing ast.ts, extracts all interface definitions, classifies
 * each field as child/optChild/list/prop, and generates:
 *   - defineNode()/defineLeaf() calls for all ~360 node types
 *   - KSNode union type
 *   - Schema creation with createNodeSchema()
 *   - Re-exports of KSNodeBase, getChildren
 *
 * Usage: npx tsx scripts/gen-node-defs.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const AST_PATH = path.resolve(__dirname, '../src/pipeline/ast.ts');
const OUT_PATH = path.resolve(__dirname, '../src/pipeline/node-defs.ts');

// ── Parse ast.ts ─────────────────────────────────────────────────────

interface ParsedField {
  name: string;
  typeStr: string;
  category: 'child' | 'optChild' | 'list' | 'prop';
  typeParam: string; // e.g., '<KSIdentifier>' or '' for generic
}

interface ParsedInterface {
  tsName: string;      // e.g., 'KSTypeAliasDeclaration'
  kindLiteral: string; // e.g., 'TypeAliasDeclaration'
  fields: ParsedField[];
  isLeaf: boolean;
  isProgram: boolean;
}

function classifyField(name: string, typeStr: string): ParsedField {
  const trimmed = typeStr.trim().replace(/;$/, '').trim();

  // KSNode[] or KSSpecific[] → list
  const arrayMatch = trimmed.match(/^(KS\w+|\w+)\[\]$/);
  if (arrayMatch) {
    const inner = arrayMatch[1];
    if (inner.startsWith('KS')) {
      // It's a child list
      const typeParam = inner === 'KSNode' ? '' : `<${inner}>`;
      return { name, typeStr: trimmed, category: 'list', typeParam };
    }
    // Non-KS array (e.g., readonly number[]) → prop
    return { name, typeStr: trimmed, category: 'prop', typeParam: `<${trimmed}>` };
  }

  // readonly number[] → prop
  if (trimmed.startsWith('readonly ')) {
    return { name, typeStr: trimmed, category: 'prop', typeParam: `<${trimmed}>` };
  }

  // KSNode | undefined or KSSpecific | undefined → optChild
  const optMatch = trimmed.match(/^(KS\w+)\s*\|\s*undefined$/);
  if (optMatch) {
    const inner = optMatch[1];
    const typeParam = inner === 'KSNode' ? '' : `<${inner}>`;
    return { name, typeStr: trimmed, category: 'optChild', typeParam };
  }

  // KSNode or KSSpecific → child
  if (trimmed.match(/^KS\w+$/) && !trimmed.match(/^KSNode(?:Base)?$/)) {
    // Specific typed child
    return { name, typeStr: trimmed, category: 'child', typeParam: `<${trimmed}>` };
  }
  if (trimmed === 'KSNode') {
    return { name, typeStr: trimmed, category: 'child', typeParam: '' };
  }

  // Everything else → prop
  let propTypeParam: string;
  if (trimmed === 'string') propTypeParam = '<string>';
  else if (trimmed === 'boolean') propTypeParam = '<boolean>';
  else if (trimmed === 'number') propTypeParam = '<number>';
  else propTypeParam = `<${trimmed}>`;

  return { name, typeStr: trimmed, category: 'prop', typeParam: propTypeParam };
}

function parseInterfaces(source: string): ParsedInterface[] {
  const results: ParsedInterface[] = [];

  // Match interface blocks
  const interfaceRe = /export interface (KS\w+)(?:\s+extends\s+KSNodeBase)?\s*\{([^}]*)\}/g;
  let match: RegExpExecArray | null;

  while ((match = interfaceRe.exec(source)) !== null) {
    const tsName = match[1];
    const body = match[2];

    // Skip KSNodeBase itself
    if (tsName === 'KSNodeBase') continue;

    // Extract kind literal
    const kindMatch = body.match(/kind:\s*'([^']+)'/);
    if (!kindMatch) continue; // shouldn't happen

    const kindLiteral = kindMatch[1];

    // Extract fields (skip kind, pos, end, text, children)
    const skipFields = new Set(['kind', 'pos', 'end', 'text', 'children']);
    const fields: ParsedField[] = [];

    const fieldRe = /(\w+):\s*(.+?);/g;
    let fieldMatch: RegExpExecArray | null;
    while ((fieldMatch = fieldRe.exec(body)) !== null) {
      const fieldName = fieldMatch[1];
      const fieldType = fieldMatch[2].trim();
      if (skipFields.has(fieldName)) continue;
      fields.push(classifyField(fieldName, fieldType));
    }

    const isProgram = tsName === 'KSProgram';

    results.push({
      tsName,
      kindLiteral,
      fields,
      isLeaf: fields.length === 0,
      isProgram,
    });
  }

  return results;
}

// ── Generate node-defs.ts ────────────────────────────────────────────

function generateNodeDefs(interfaces: ParsedInterface[]): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Schema-first node definitions for the KSC AST.`);
  lines.push(` *`);
  lines.push(` * AUTO-GENERATED by scripts/gen-node-defs.ts from ast.ts.`);
  lines.push(` * This is the single source of truth for node types.`);
  lines.push(` *`);
  lines.push(` * Each defineNode()/defineLeaf() call produces:`);
  lines.push(` *   - Runtime schema entry (kind, child fields, prop fields)`);
  lines.push(` *   - TypeScript type via InferNode<typeof Def>`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`import {`);
  lines.push(`  defineNode, defineLeaf, child, optChild, list, prop,`);
  lines.push(`  createNodeSchema,`);
  lines.push(`} from '../../libs/ag-schema/src/index.js';`);
  lines.push(`import type { InferNode, NodeDef } from '../../libs/ag-schema/src/index.js';`);
  lines.push(``);

  // Forward-declare the KSNode type for self-referential fields
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(`// Base type (re-exported from ast.ts)`);
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(``);
  lines.push(`export { KSNodeBase } from './ast.js';`);
  lines.push(``);

  // Group by category
  const complex = interfaces.filter(i => !i.isLeaf);
  const leaves = interfaces.filter(i => i.isLeaf);

  // Complex nodes
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(`// Node definitions (nodes with named fields)`);
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(``);

  for (const iface of complex) {
    const defName = iface.tsName.replace(/^KS/, '');

    // Build fields object
    const fieldEntries: string[] = [];
    for (const f of iface.fields) {
      const builderCall = `${f.category}${f.typeParam}()`;
      fieldEntries.push(`  ${f.name}: ${builderCall},`);
    }

    if (fieldEntries.length === 0) {
      lines.push(`export const ${defName}Def = defineLeaf('${iface.kindLiteral}');`);
    } else {
      lines.push(`export const ${defName}Def = defineNode('${iface.kindLiteral}', {`);
      for (const entry of fieldEntries) {
        lines.push(entry);
      }
      lines.push(`});`);
    }
    lines.push(``);
  }

  // Leaf nodes
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(`// Leaf node definitions (tokens, keywords, trivia, simple nodes)`);
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(``);

  for (const iface of leaves) {
    const defName = iface.tsName.replace(/^KS/, '');
    lines.push(`export const ${defName}Def = defineLeaf('${iface.kindLiteral}');`);
  }

  lines.push(``);

  // Type aliases
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(`// Inferred TypeScript types`);
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(``);

  for (const iface of interfaces) {
    const defName = iface.tsName.replace(/^KS/, '');
    lines.push(`export type ${iface.tsName} = InferNode<typeof ${defName}Def>;`);
  }

  lines.push(``);

  // KSNode union
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(`// KSNode union type`);
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(``);
  lines.push(`export type KSNode =`);
  for (let i = 0; i < interfaces.length; i++) {
    const sep = i === interfaces.length - 1 ? ';' : '';
    lines.push(`  | ${interfaces[i].tsName}${sep}`);
  }

  lines.push(``);

  // All defs array
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(`// All node definitions (for schema creation)`);
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(``);
  lines.push(`export const allNodeDefs: NodeDef[] = [`);
  for (const iface of interfaces) {
    const defName = iface.tsName.replace(/^KS/, '');
    lines.push(`  ${defName}Def,`);
  }
  lines.push(`];`);
  lines.push(``);

  // Schema creation
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(`// Schema (runtime introspection, derived getChildren, completeness checking)`);
  lines.push(`// ═══════════════════════════════════════════════════════════════════════`);
  lines.push(``);
  lines.push(`export const ksNodeSchema = createNodeSchema<KSNode>(allNodeDefs);`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Schema-derived getChildren. Replaces the hand-written version in ast.ts.`);
  lines.push(` *`);
  lines.push(` * For Program → compilationUnits (from named children).`);
  lines.push(` * For nodes with named children → collects them in declaration order.`);
  lines.push(` * For leaf nodes → falls back to flat children array.`);
  lines.push(` */`);
  lines.push(`export const getChildren: (node: KSNode) => KSNode[] = ksNodeSchema.getChildren;`);
  lines.push(``);

  return lines.join('\n');
}

// ── Main ─────────────────────────────────────────────────────────────

const source = fs.readFileSync(AST_PATH, 'utf-8');
const interfaces = parseInterfaces(source);

console.log(`Parsed ${interfaces.length} interfaces:`);
console.log(`  Complex: ${interfaces.filter(i => !i.isLeaf).length}`);
console.log(`  Leaf:    ${interfaces.filter(i => i.isLeaf).length}`);

const output = generateNodeDefs(interfaces);
fs.writeFileSync(OUT_PATH, output, 'utf-8');
console.log(`\nGenerated ${OUT_PATH}`);
console.log(`  ${output.split('\n').length} lines`);
