// Simulated protobuf generated file
// In real code this would be generated by protoc-gen-ts / grpc-web

export class Person {
  name: string = '';
  age: number = 0;
  private array_: unknown[] = [];

  getName(): string { return this.array_[0] as string; }
  setName(value: string): void { this.array_[0] = value; }
  getAge(): number { return this.array_[1] as number; }
  setAge(value: number): void { this.array_[1] = value; }
  getAddress(): Address { return this.array_[2] as Address; }
  toObject(): { name: string; age: number } {
    return { name: this.getName(), age: this.getAge() };
  }
  serializeBinary(): Uint8Array { return new Uint8Array(); }
}

export class Address {
  street: string = '';
  city: string = '';
  private array_: unknown[] = [];

  getStreet(): string { return this.array_[0] as string; }
  setStreet(value: string): void { this.array_[0] = value; }
  getCity(): string { return this.array_[1] as string; }
  setCity(value: string): void { this.array_[1] = value; }
}

// Generic wrapper for testing fuzzy typeString matching
export class Wrapper<T> {
  private value_: T | null = null;
  getValue(): T | null { return this.value_; }
  setValue(v: T): void { this.value_ = v; }
}
