/**
 * Functor 2: Analysis Compilation (Generic AG Evaluator Generator)
 *
 * compileAnalysis(AnalysisSpec) → CompiledAnalyzer
 *
 * Takes a declarative analysis specification and produces:
 *   - evaluator.ts  — KSCDNode class with typed cache, switch dispatch
 *   - attr-types.ts — KSCAttrMap interface
 *   - dep graph     — static attribute dependency graph
 *
 * This module is fully generic — zero knowledge of specific grammars or
 * analysis patterns. Attribute method bodies are generated from direction-typed
 * declarations (SynAttr, InhAttr, CollectionAttr) with optional per-kind
 * equations and parameterized attribute support (JastAdd-style).
 *
 * Equation functions are referenced directly (not as strings). compile.ts
 * reads fn.name to generate imports and call expressions. Dependencies are
 * inferred from withDeps() metadata on the function references.
 */

import type {
  AnalysisSpec,
  AttrDecl,
  SynAttr,
  InhAttr,
  CollectionAttr,
  CompiledAnalyzer,
  AttributeDepGraph,
  AttrExpr,
  ParamDef,
} from './types.js';
import { collectDepsForAttr, isCodeLiteral } from './types.js';

// ── AttrExpr → generated code ───────────────────────────────────────

/**
 * Convert an AttrExpr value to the code string emitted in the generated evaluator.
 *
 * - Function → fn.name(this) or fn.name(this, param)
 * - null → 'null'
 * - number → the number as string
 * - boolean → 'true' / 'false'
 * - CodeLiteral → the raw code string
 */
function emitExpr(value: AttrExpr, param?: ParamDef): string {
  if (value === null) return 'null';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return String(value);
  if (isCodeLiteral(value)) return value.code;
  // Function
  if (param) return `${value.name}(this, ${param.name})`;
  return `${value.name}(this)`;
}

// ── Collect equation function names for auto-import ─────────────────

function collectEquationFunctions(attrs: AttrDecl[]): Set<string> {
  const names = new Set<string>();

  function addIfFn(v: AttrExpr | undefined) {
    if (typeof v === 'function' && v.name) names.add(v.name);
  }

  for (const attr of attrs) {
    switch (attr.direction) {
      case 'syn':
        addIfFn(attr.default);
        if (attr.equations) {
          for (const fn of Object.values(attr.equations)) {
            if (fn.name) names.add(fn.name);
          }
        }
        break;
      case 'inh':
        addIfFn(attr.rootValue);
        if (attr.parentEquations) {
          for (const fn of Object.values(attr.parentEquations)) {
            if (fn.name) names.add(fn.name);
          }
        }
        break;
      case 'collection':
        addIfFn(attr.init);
        break;
    }
  }

  return names;
}

// ── Build dep graph ──────────────────────────────────────────────────

function buildDepGraphFromAttrs(attrs: AttrDecl[]): {
  edges: [string, string][];
  order: string[];
} {
  const depMap = new Map<string, Set<string>>();
  const edges: [string, string][] = [];

  for (const attr of attrs) {
    const deps = new Set(collectDepsForAttr(attr));
    depMap.set(attr.name, deps);
    for (const dep of deps) {
      edges.push([attr.name, dep]);
    }
  }

  // Topological sort
  const order: string[] = [];
  const visited = new Set<string>();
  const inStack = new Set<string>();

  function visit(name: string) {
    if (visited.has(name)) return;
    if (inStack.has(name)) throw new Error(`Cycle in dep graph: ${name}`);
    inStack.add(name);
    const neighbors = depMap.get(name);
    if (neighbors) for (const dep of neighbors) visit(dep);
    inStack.delete(name);
    visited.add(name);
    order.push(name);
  }

  for (const name of depMap.keys()) visit(name);

  return { edges, order };
}

// ── Generate attr-types.ts ───────────────────────────────────────────

function generateAttrTypes(
  attrs: AttrDecl[],
  spec: AnalysisSpec,
  importPaths: { specImportPath: string },
): string {
  const nonParam = attrs.filter(a => !a.parameter);
  const L: string[] = [];
  L.push(`/**`);
  L.push(` * AUTO-GENERATED by compileAnalysis — do not edit.`);
  L.push(` *`);
  L.push(` * Type map for AG attributes (${nonParam.length} non-parameterized of ${attrs.length} total).`);
  L.push(` */`);
  L.push(``);
  // Spec-provided domain type imports (if any)
  if (spec.evaluatorSetup?.attrTypesImports) {
    const importLines = spec.evaluatorSetup.attrTypesImports(importPaths);
    for (const line of importLines) L.push(line);
    L.push(``);
  }
  L.push(`export interface KSCAttrMap {`);
  for (const a of nonParam) {
    const t = a.type.includes('=>') ? `(${a.type})` : a.type;
    L.push(`  ${a.name}: ${t};`);
  }
  L.push(`}`);
  L.push(``);
  return L.join('\n');
}

// ── Direction-aware method body generation ──────────────────────────

function generateSynBody(L: string[], a: SynAttr): void {
  const p = a.parameter;

  if (a.equations && Object.keys(a.equations).length > 0) {
    if (p) {
      L.push(`      let _r: ${a.type};`);
      L.push(`      switch (this.node.kind) {`);
      for (const [kind, fn] of Object.entries(a.equations)) {
        L.push(`        case '${kind}': _r = ${emitExpr(fn, p)}; break;`);
      }
      L.push(`        default: _r = ${emitExpr(a.default, p)}; break;`);
      L.push(`      }`);
      L.push(`      this._pc_${a.name}.set(${p.name}, _r);`);
      L.push(`      return _r;`);
    } else {
      L.push(`      switch (this.node.kind) {`);
      for (const [kind, fn] of Object.entries(a.equations)) {
        L.push(`        case '${kind}': return this._c_${a.name} = ${emitExpr(fn)};`);
      }
      L.push(`        default: return this._c_${a.name} = ${emitExpr(a.default)};`);
      L.push(`      }`);
    }
  } else {
    if (p) {
      L.push(`      const _r = ${emitExpr(a.default, p)};`);
      L.push(`      this._pc_${a.name}.set(${p.name}, _r);`);
      L.push(`      return _r;`);
    } else {
      L.push(`      return this._c_${a.name} = ${emitExpr(a.default)};`);
    }
  }
}

function generateInhBody(L: string[], a: InhAttr): void {
  const p = a.parameter;

  // Root value
  if (p) {
    L.push(`      if (this.isRoot) {`);
    L.push(`        const _r = ${emitExpr(a.rootValue, p)};`);
    L.push(`        this._pc_${a.name}.set(${p.name}, _r);`);
    L.push(`        return _r;`);
    L.push(`      }`);
  } else {
    L.push(`      if (this.isRoot) {`);
    L.push(`        return this._c_${a.name} = ${emitExpr(a.rootValue)};`);
    L.push(`      }`);
  }

  // Parent equations (return T to override, undefined to copy-down)
  if (a.parentEquations && Object.keys(a.parentEquations).length > 0) {
    L.push(`      const _pKind = this.parent!.node.kind;`);
    L.push(`      let _override: ${a.type} | undefined = undefined;`);
    L.push(`      switch (_pKind) {`);
    for (const [kind, fn] of Object.entries(a.parentEquations)) {
      L.push(`        case '${kind}': _override = ${emitExpr(fn, p)}; break;`);
    }
    L.push(`      }`);
    L.push(`      if (_override !== undefined) {`);
    if (p) {
      L.push(`        this._pc_${a.name}.set(${p.name}, _override);`);
      L.push(`        return _override;`);
    } else {
      L.push(`        return this._c_${a.name} = _override;`);
    }
    L.push(`      }`);
  }

  // Copy-down from parent
  if (p) {
    L.push(`      const _r = this.parent!.${a.name}(${p.name});`);
    L.push(`      this._pc_${a.name}.set(${p.name}, _r);`);
    L.push(`      return _r;`);
  } else {
    L.push(`      return this._c_${a.name} = this.parent!.${a.name}();`);
  }
}

function generateCollBody(L: string[], a: CollectionAttr): void {
  const p = a.parameter;

  L.push(`      const _combine = ${a.combine.code};`);
  L.push(`      let _result = ${emitExpr(a.init)};`);
  if (p) {
    L.push(`      for (const child of this.children) {`);
    L.push(`        _result = _combine(_result, child.${a.name}(${p.name}));`);
    L.push(`      }`);
    L.push(`      this._pc_${a.name}.set(${p.name}, _result);`);
    L.push(`      return _result;`);
  } else {
    L.push(`      for (const child of this.children) {`);
    L.push(`        _result = _combine(_result, child.${a.name}());`);
    L.push(`      }`);
    L.push(`      return this._c_${a.name} = _result;`);
  }
}

// ── Method generation ────────────────────────────────────────────────

function generateMethod(L: string[], a: AttrDecl): void {
  const p = a.parameter;

  if (p) {
    const cycKey = `'${a.name}:' + ${p.name}`;
    L.push(`  ${a.name}(${p.name}: ${p.type}): ${a.type} {`);
    L.push(`    if (this._pc_${a.name}.has(${p.name})) return this._pc_${a.name}.get(${p.name})!;`);
    L.push(`    if (this._cyc.has(${cycKey})) throw new Error(\`Circular attribute access: '${a.name}(\${${p.name}})' on \${this.node.kind}\`);`);
    L.push(`    this._cyc.add(${cycKey});`);
    L.push(`    try {`);
  } else {
    L.push(`  ${a.name}(): ${a.type} {`);
    L.push(`    if (this._c_${a.name} !== undefined) return this._c_${a.name};`);
    L.push(`    if (this._cyc.has('${a.name}')) throw new Error(\`Circular attribute access: '${a.name}' on \${this.node.kind}\`);`);
    L.push(`    this._cyc.add('${a.name}');`);
    L.push(`    try {`);
  }

  // Direction-specific body
  switch (a.direction) {
    case 'syn': generateSynBody(L, a as SynAttr); break;
    case 'inh': generateInhBody(L, a as InhAttr); break;
    case 'collection': generateCollBody(L, a as CollectionAttr); break;
  }

  if (p) {
    const cycKey = `'${a.name}:' + ${p.name}`;
    L.push(`    } finally { this._cyc.delete(${cycKey}); }`);
  } else {
    L.push(`    } finally { this._cyc.delete('${a.name}'); }`);
  }
  L.push(`  }`);
  L.push(``);
}

// ── Generate evaluator.ts ────────────────────────────────────────────

function generateEvaluator(
  attrs: AttrDecl[],
  graph: { edges: [string, string][]; order: string[] },
  spec: AnalysisSpec,
  specImportPath: string,
  grammarImportPath: string,
  analysisImportPath: string,
): string {
  const nonParam = attrs.filter(a => !a.parameter);
  const paramAttrs = attrs.filter(a => !!a.parameter);
  const L: string[] = [];

  // ── Header ──
  L.push(`/**`);
  L.push(` * AUTO-GENERATED by compileAnalysis — do not edit.`);
  L.push(` *`);
  L.push(` * KSC Compiled Evaluator — fully static AG pipeline.`);
  L.push(` * KSCDNode: standalone decorated node with typed cache fields,`);
  L.push(` * switch-based dispatch, and direct equation function calls.`);
  L.push(` */`);
  L.push(``);

  // ── Generic imports ──
  L.push(`import type { KSNode } from '${grammarImportPath}';`);
  L.push(`import { getChildFields } from '${grammarImportPath}';`);
  L.push(`import type { KSCAttrMap } from './attr-types.js';`);
  L.push(`import type { Ctx } from '${analysisImportPath}/ctx.js';`);
  L.push(`import type { AttributeDepGraph } from '${analysisImportPath}/types.js';`);
  L.push(``);

  // ── Auto-generated equation imports ──
  const eqFnNames = collectEquationFunctions(attrs);
  if (eqFnNames.size > 0) {
    const equationsPath = specImportPath.replace(/\/spec\.js$/, '/equations.js');
    L.push(`// Equation imports (auto-generated from function references)`);
    L.push(`import {`);
    for (const name of eqFnNames) {
      L.push(`  ${name},`);
    }
    L.push(`} from '${equationsPath}';`);
    L.push(``);
  }

  // ── Spec-provided imports ──
  if (spec.evaluatorSetup) {
    const importLines = spec.evaluatorSetup.imports({
      specImportPath,
    });
    for (const line of importLines) {
      L.push(line);
    }
    L.push(``);
  }

  // ── Spec-provided module-level setup ──
  if (spec.evaluatorSetup?.moduleSetup && spec.evaluatorSetup.moduleSetup.length > 0) {
    L.push(`// ── Spec-provided module setup ──`);
    L.push(``);
    for (const line of spec.evaluatorSetup.moduleSetup) {
      L.push(line);
    }
    L.push(``);
  }

  // ── KSCDNode class ──
  L.push(`// ── KSCDNode: typed cache + switch dispatch ──`);
  L.push(``);

  L.push(`export class KSCDNode implements Ctx {`);

  // Navigation fields
  L.push(`  readonly node: KSNode;`);
  L.push(`  readonly parent: KSCDNode | undefined;`);
  L.push(`  readonly children: readonly KSCDNode[];`);
  L.push(`  readonly isRoot: boolean;`);
  L.push(`  readonly fieldName: string | undefined;`);
  L.push(``);

  // Typed cache fields — non-parameterized
  if (nonParam.length > 0) {
    L.push(`  // Typed cache — undefined = not yet computed`);
    for (const a of nonParam) {
      const ct = a.type.includes('=>') ? `(${a.type})` : a.type;
      L.push(`  private _c_${a.name}: ${ct} | undefined = undefined;`);
    }
    L.push(``);
  }

  // Typed cache fields — parameterized (Map-based)
  if (paramAttrs.length > 0) {
    L.push(`  // Parameterized cache — Map<param, value>`);
    for (const a of paramAttrs) {
      const ct = a.type.includes('=>') ? `(${a.type})` : a.type;
      L.push(`  private _pc_${a.name} = new Map<${a.parameter!.type}, ${ct}>();`);
    }
    L.push(``);
  }

  L.push(`  private _cyc = new Set<string>();`);
  L.push(``);

  // Constructor
  L.push(`  constructor(`);
  L.push(`    node: KSNode,`);
  L.push(`    parent: KSCDNode | undefined,`);
  L.push(`    children: KSCDNode[],`);
  L.push(`    fieldName: string | undefined,`);
  L.push(`  ) {`);
  L.push(`    this.node = node;`);
  L.push(`    this.parent = parent;`);
  L.push(`    this.children = children;`);
  L.push(`    this.isRoot = !parent;`);
  L.push(`    this.fieldName = fieldName;`);
  L.push(`  }`);
  L.push(``);

  // attr() switch dispatch
  L.push(`  // ── Attribute access (string-based, for equations and serialization) ──`);
  L.push(``);
  L.push(`  attr<K extends string & keyof KSCAttrMap>(name: K): KSCAttrMap[K];`);
  L.push(`  attr(name: string, ...args: unknown[]): any {`);
  L.push(`    switch (name) {`);
  for (const a of attrs) {
    if (a.parameter) {
      L.push(`      case '${a.name}': return this.${a.name}(args[0] as ${a.parameter.type});`);
    } else {
      L.push(`      case '${a.name}': return this.${a.name}();`);
    }
  }
  L.push(`      default: throw new Error(\`Unknown attribute '\${name}' on \${this.node.kind ?? 'node'}\`);`);
  L.push(`    }`);
  L.push(`  }`);
  L.push(``);

  // Structural queries
  L.push(`  // ── Structural queries ──`);
  L.push(``);
  L.push(`  parentIs(kind: string, field?: string): boolean {`);
  L.push(`    if (!this.parent) return false;`);
  L.push(`    if (this.parent.node.kind !== kind) return false;`);
  L.push(`    if (field !== undefined) return this.fieldName === field;`);
  L.push(`    return true;`);
  L.push(`  }`);
  L.push(``);

  // findFileName helper — public (Ctx interface)
  const rootKind = spec.grammarConfig.rootKind;
  const fileNameField = spec.grammarConfig.fileNameField;
  L.push(`  findFileName(): string {`);
  L.push(`    let current: KSCDNode | undefined = this.parent;`);
  L.push(`    while (current && current.node.kind !== '${rootKind}') {`);
  L.push(`      current = current.parent;`);
  L.push(`    }`);
  L.push(`    return current ? (current.node as any).${fileNameField} : '<unknown>';`);
  L.push(`  }`);
  L.push(``);

  // Spec-provided helper methods
  if (spec.evaluatorSetup?.helperMethods && spec.evaluatorSetup.helperMethods.length > 0) {
    for (const line of spec.evaluatorSetup.helperMethods) {
      L.push(line);
    }
    L.push(``);
  }

  // ── Direct typed attribute methods ──
  L.push(`  // ── Direct typed attribute methods ──`);
  L.push(``);
  for (const a of attrs) {
    generateMethod(L, a);
  }

  L.push(`}`);
  L.push(``);

  // ── buildKSCTree ──
  L.push(`// ── Schema-aware tree builder ──`);
  L.push(``);
  L.push(`export function buildKSCTree(root: KSNode): KSCDNode {`);
  L.push(`  function build(`);
  L.push(`    raw: KSNode,`);
  L.push(`    parent: KSCDNode | undefined,`);
  L.push(`    fieldName: string | undefined,`);
  L.push(`  ): KSCDNode {`);
  L.push(`    const children: KSCDNode[] = [];`);
  L.push(`    const dnode = new KSCDNode(raw, parent, children, fieldName);`);
  L.push(``);
  L.push(`    const fields = getChildFields(raw.kind);`);
  L.push(`    for (const field of fields) {`);
  L.push(`      const val = (raw as any)[field];`);
  L.push(`      if (val == null) continue;`);
  L.push(`      if (Array.isArray(val)) {`);
  L.push(`        for (const item of val) {`);
  L.push(`          if (item == null) continue;`);
  L.push(`          children.push(build(item as KSNode, dnode, field));`);
  L.push(`        }`);
  L.push(`      } else {`);
  L.push(`        children.push(build(val as KSNode, dnode, field));`);
  L.push(`      }`);
  L.push(`    }`);
  L.push(``);
  L.push(`    return dnode;`);
  L.push(`  }`);
  L.push(``);
  L.push(`  return build(root, undefined, undefined);`);
  L.push(`}`);
  L.push(``);

  // ── Static dependency graph ──
  L.push(`// ── Static dependency graph ──`);
  L.push(``);
  L.push(`const KSC_STATIC_DEP_GRAPH: AttributeDepGraph = {`);
  L.push(`  attributes: [`);
  for (const a of attrs) L.push(`    '${a.name}',`);
  L.push(`  ],`);
  L.push(`  edges: [`);
  for (const [from, to] of graph.edges) {
    L.push(`    ['${from}', '${to}'],`);
  }
  L.push(`  ],`);
  L.push(`  order: [`);
  for (const name of graph.order) L.push(`    '${name}',`);
  L.push(`  ],`);
  L.push(`  declarations: {`);
  for (const a of attrs) L.push(`    ${a.name}: { direction: '${a.direction}' },`);
  L.push(`  },`);
  L.push(`};`);
  L.push(``);

  // ── Spec-provided evaluation entry point ──
  if (spec.evaluatorSetup?.evaluateBody) {
    L.push(`// ── Evaluation ──`);
    L.push(``);
    const bodyLines = spec.evaluatorSetup.evaluateBody({
      specImportPath,
    });
    for (const line of bodyLines) L.push(line);
  }

  return L.join('\n') + '\n';
}

// ═════════════════════════════════════════════════════════════════════
// Public API
// ═════════════════════════════════════════════════════════════════════

export interface CompileAnalysisOpts {
  /** Import path for the analysis spec (used in generated evaluator). */
  specImportPath?: string;
  /** Import path from generated evaluator to grammar output (e.g. '../grammar/index.js'). */
  grammarImportPath?: string;
  /** Import path from generated files to analysis/ machinery (e.g. '../../../analysis'). */
  analysisImportPath?: string;
}

export function compileAnalysis(
  spec: AnalysisSpec,
  opts?: CompileAnalysisOpts,
): CompiledAnalyzer {
  const specImportPath = opts?.specImportPath ?? './spec.js';
  const grammarImportPath = opts?.grammarImportPath ?? '../grammar/index.js';
  const analysisImportPath = opts?.analysisImportPath ?? '../../../analysis';

  // 1. Read attrs directly from spec (no automatic derivation)
  const allAttrs = spec.attrs;

  // 2. Build dep graph and topo sort
  const graph = buildDepGraphFromAttrs(allAttrs);

  // 3. Generate evaluator
  const evaluatorContent = generateEvaluator(allAttrs, graph, spec, specImportPath, grammarImportPath, analysisImportPath);

  // 4. Generate attr-types
  const attrTypesContent = generateAttrTypes(allAttrs, spec, {
    specImportPath,
  });

  // 5. Build result
  const depGraph: AttributeDepGraph = {
    attributes: allAttrs.map(a => a.name),
    edges: graph.edges,
    order: graph.order,
    declarations: Object.fromEntries(allAttrs.map(a => [a.name, { direction: a.direction }])),
  };

  return {
    evaluatorFile: { path: 'evaluator.ts', content: evaluatorContent },
    attrTypesFile: { path: 'attr-types.ts', content: attrTypesContent },
    attrs: allAttrs.map(a => ({
      name: a.name,
      direction: a.direction,
      type: a.type,
    })),
    depGraph,
  };
}
