// AUTO GENERATED by protoc-gen-ts — DO NOT EDIT
// source: proto/event.proto

export class AuditEvent {
  action: string = '';
  userId: string = '';
  timestamp: number = 0;
  metadata: string = '';
  private array_: unknown[] = [];

  getAction(): string { return this.array_[0] as string; }
  setAction(value: string): void { this.array_[0] = value; }
  getUserId(): string { return this.array_[1] as string; }
  setUserId(value: string): void { this.array_[1] = value; }
  getTimestamp(): number { return this.array_[2] as number; }
  setTimestamp(value: number): void { this.array_[2] = value; }
  getMetadata(): string { return this.array_[3] as string; }
  setMetadata(value: string): void { this.array_[3] = value; }

  toObject(): { action: string; userId: string; timestamp: number; metadata: string } {
    return {
      action: this.getAction(),
      userId: this.getUserId(),
      timestamp: this.getTimestamp(),
      metadata: this.getMetadata(),
    };
  }

  serializeBinary(): Uint8Array { return new Uint8Array(); }
}

export class BatchEvents {
  eventsList: AuditEvent[] = [];
  private array_: unknown[] = [];

  getEventsList(): AuditEvent[] { return this.array_[0] as AuditEvent[]; }
  setEventsList(value: AuditEvent[]): void { this.array_[0] = value; }
  addEvents(value: AuditEvent): void {
    const list = this.getEventsList() || [];
    list.push(value);
    this.array_[0] = list;
  }

  serializeBinary(): Uint8Array { return new Uint8Array(); }
}
