// AUTO GENERATED by protoc-gen-ts — DO NOT EDIT
// source: proto/user.proto

export class User {
  name: string = '';
  email: string = '';
  age: number = 0;
  role: string = '';
  private array_: unknown[] = [];

  getName(): string { return this.array_[0] as string; }
  setName(value: string): void { this.array_[0] = value; }
  getEmail(): string { return this.array_[1] as string; }
  setEmail(value: string): void { this.array_[1] = value; }
  getAge(): number { return this.array_[2] as number; }
  setAge(value: number): void { this.array_[2] = value; }
  getRole(): string { return this.array_[3] as string; }
  setRole(value: string): void { this.array_[3] = value; }
  getProfile(): UserProfile { return this.array_[4] as UserProfile; }
  setProfile(value: UserProfile): void { this.array_[4] = value; }

  toObject(): { name: string; email: string; age: number; role: string } {
    return {
      name: this.getName(),
      email: this.getEmail(),
      age: this.getAge(),
      role: this.getRole(),
    };
  }

  serializeBinary(): Uint8Array { return new Uint8Array(); }
  static deserializeBinary(_bytes: Uint8Array): User { return new User(); }
}

export class UserProfile {
  bio: string = '';
  avatarUrl: string = '';
  private array_: unknown[] = [];

  getBio(): string { return this.array_[0] as string; }
  setBio(value: string): void { this.array_[0] = value; }
  getAvatarUrl(): string { return this.array_[1] as string; }
  setAvatarUrl(value: string): void { this.array_[1] = value; }

  toObject(): { bio: string; avatarUrl: string } {
    return { bio: this.getBio(), avatarUrl: this.getAvatarUrl() };
  }
}

export class UpdateUserRequest {
  userId: string = '';
  user: User | null = null;
  fieldMask: string[] = [];
  private array_: unknown[] = [];

  getUserId(): string { return this.array_[0] as string; }
  setUserId(value: string): void { this.array_[0] = value; }
  getUser(): User | null { return this.array_[1] as User | null; }
  setUser(value: User): void { this.array_[1] = value; }
  getFieldMaskList(): string[] { return this.array_[2] as string[]; }
  setFieldMaskList(value: string[]): void { this.array_[2] = value; }

  toObject(): { userId: string; user: ReturnType<User['toObject']> | null; fieldMask: string[] } {
    const u = this.getUser();
    return {
      userId: this.getUserId(),
      user: u ? u.toObject() : null,
      fieldMask: this.getFieldMaskList(),
    };
  }

  serializeBinary(): Uint8Array { return new Uint8Array(); }
}

export class UpdateUserResponse {
  success: boolean = false;
  message: string = '';
  private array_: unknown[] = [];

  getSuccess(): boolean { return this.array_[0] as boolean; }
  setSuccess(value: boolean): void { this.array_[0] = value; }
  getMessage(): string { return this.array_[1] as string; }
  setMessage(value: string): void { this.array_[1] = value; }

  serializeBinary(): Uint8Array { return new Uint8Array(); }
}
